### PR TITLE
Main - Add missing gauges

### PR DESCRIPTION
**Pull request by JeremyParish69**
-Add XPRT/USDC 14-day gauge 3528
-add gauges for pools: 3, 625, 633
-update gauges for pools: 573, 574, 592, 600, 601, 602, 604, 611, 613, 617, 641, 643, 648
Edit: and 2 gauges for 716

### CODE REVIEW

**Comment by puneet2019** [comment]
can you also add a trade router to pool 719?

**Comment by JeremyParish69** [comment]
> can you also add a trade router to pool 719?

The upgraded Trade router in this branch will not require manually adding pools to it anymore.

**Comment by angrymouse** [comment]
Also, can 716 be included in LockupAblePoolIDs?

**Comment by JeremyParish69** [comment]
> Also, can 716 be included in LockupAblePoolIDs?

This upgraded code will not require manually specifying lockup-able Pools. By default, all pool will be lockup-able.

**Comment by angrymouse** [comment]
Merged, but I still can't see incentives for xprt/usdc or rowan/asvt on main app and frontier. What's problem?

**Pull request merged**
