### PR TITLE
[Frontier] Add Another.Software Validator Token

### PR DESCRIPTION
**Pull request by angrymouse**

### CODE REVIEW

**Review by ankurdotb — CHANGES_REQUESTED** [review]
@angrymouse I can't see the ASVT token on the [CW20 asset listi on Mintscan](https://www.mintscan.io/juno/assets) yet, which is likely because I don't see the token on the [Cosmos chain registry assetlist for Juno](https://github.com/cosmos/chain-registry/blob/master/juno/assetlist.json). Please add your asset/token to the Cosmos chain registry first, as a lot of Cosmos apps like the Osmosis frontend and others rely on this as the canonical asset list in their apps.

You could set this PR to draft while the PR upstream on chain registry goes through the merge/approval process, and then come back to this one to add to Frontier.

**Comment by angrymouse** [comment]
Thank you! WIll do, don't close PR yet

**Comment by JeremyParish69** [comment]
Can we try to get some liquidity added before listing?

**Comment by angrymouse** [comment]
> Can we try to get some liquidity added before listing?

Like create first pool and add first liquidity here?

**Comment by angrymouse** [comment]
How can we do it before listing? Is there another UIs or should we do through cosmjs?

**Comment by angrymouse** [comment]
Ah, yes, clone this repo and add to config locally, then create pool

**Comment by JeremyParish69** [comment]
> How can we do it before listing? Is there another UIs or should we do through cosmjs?

You can also use the preview from the vercel deployment link above.

**Comment by angrymouse** [comment]
Conflict of changes for merging, will re-open in a day with created pool

**Pull request closed without merging**
