### PR TITLE
chore: web package debugger configuration for vs code

### PR DESCRIPTION
**Pull request by p0mvn**
Progress towards: https://github.com/osmosis-labs/osmosis-frontend/issues/2739

## What is the purpose of the change

This PR adds a VS code debugger configuration.

It enables starting the app and setting breakpoints in the `web` package. I'm still investigating how to achieve setting breakpoints in other packages and tracking progress in #2739.

### CODE REVIEW

**Comment by jonator** [comment]
This is just for stepping through the backend?

**Comment by jonator** [comment]
For client, it's possible to set breakpoints in the source maps in the source tab in chrome dev tools

**Review by MaxMillington — APPROVED** [review]
can I introduce you to `console.log` 😂

**Comment by p0mvn** [comment]
> This is just for stepping through the backend?
> For client, it's possible to set breakpoints in the source maps in the source tab in chrome dev tools

This is still only relevant to the `web` package (client) but it is already helping me run and debug it directly through vs code, offering more convenience. I will continue investigating how to also enable other packages.

> can I introduce you to console.log 😂

I like being in the driver's seat 🤣

**Comment by p0mvn** [comment]
Merging with one ACK since this is a config update

**Pull request merged**
