### PR TITLE
Add Cerberus Coin

### PR DESCRIPTION
**Pull request by dylanschultzie**
There aren't any pools created quite yet.

Signed-off-by: Dylan Schultz <dylanschultz311@gmail.com>

### CODE REVIEW

**Comment by jonator** [comment]
Please keep us updated for when you create the pool!

**Comment by JeremyParish69** [comment]
not sure why this was closed, but the tx explorer URL shouldn't have the '$' in it. Also I believe the image files should be named by the symbol, so crbrus.png, not cerberus.png

**Comment by sunnya97** [comment]
@dylanschultzie can you fix the merge conflicts pls

**Comment by dylanschultzie** [comment]
@sunnya97 fixed, but the formatting got all knackered. What formatter is being used? VS Code's prettier makes it far worse.

**Comment by JeremyParish69** [comment]
Please have the 'cerberus' bech32 prefix registered to [SLIP173](https://github.com/satoshilabs/slips/blob/master/slip-0173.md)

Please register Cerberus to [Osmosis Assetlists repo](https://github.com/osmosis-labs/assetlists)

Please add 'ibc-go' as a feature, since it looks like they're beyond Cosmos SDK v0.43.

There is no Asset price oracle. Since there is no CoinGecko id yet, could we use pool 658 for a derived price?

Using a HUAHUA pool is a bit unusual--can we at least add $1000-worth of liquidity before adding it to the Trade page?
Is there going to be a direct OSMO pool (not required)?

**Comment by dylanschultzie** [comment]
> Please have the 'cerberus' bech32 prefix registered to [SLIP173](https://github.com/satoshilabs/slips/blob/master/slip-0173.md)
✅ 

> Please register Cerberus to [Osmosis Assetlists repo](https://github.com/osmosis-labs/assetlists)
In progress

> Please add 'ibc-go' as a feature, since it looks like they're beyond Cosmos SDK v0.43.
✅ 

> There is no Asset price oracle. Since there is no CoinGecko id yet, could we use pool 658 for a derived price?
✅

**Comment by cerberus-zone** [comment]
> Please have the 'cerberus' bech32 prefix registered to [SLIP173](https://github.com/satoshilabs/slips/blob/master/slip-0173.md)
> 
> Please register Cerberus to [Osmosis Assetlists repo](https://github.com/osmosis-labs/assetlists)
> 
> Please add 'ibc-go' as a feature, since it looks like they're beyond Cosmos SDK v0.43.
> 
> There is no Asset price oracle. Since there is no CoinGecko id yet, could we use pool 658 for a derived price?
> 
> Using a HUAHUA pool is a bit unusual--can we at least add $1000-worth of liquidity before adding it to the Trade page? Is there going to be a direct OSMO pool (not required)?

Team will be adding Osmosis pool later today or tomorrow

**Comment by dylanschultzie** [comment]
Added the coingecko listing 👍

**Comment by sunnya97** [comment]
I don't think that coingecko id is right, it leads to some coin on BSC:  https://www.coingecko.com/en/coins/cerberus

Please hold off on the coingecko id until after its listed on coingecko with a price.  Until then, please use a pool price.  Would be easiest once there's an OSMO pool.

**Comment by dylanschultzie** [comment]
*maybe* added the pool price accurately?

**Comment by JeremyParish69** [comment]
> _maybe_ added the pool price accurately?

If we are going to use pool 658, then we should try to add more liquidity first.

Also, please change:
`spotPriceDestDenom: 'uhuahua',`
to:
`spotPriceDestDenom: DenomHelper.ibcDenom([{ portId: 'transfer', channelId: 'channel-113' }], 'uhuahua'),`
we can see a  similar notation for when ATOM was being used as the reference price.

and change:
`destCoinId: 'chihuahua',`
to:
`destCoinId: 'chihuahua-token',`
since chihuahua is some other token, while chihuahua-token is the coingecko id for huahua, as per the [CoinGecko coins list](https://api.coingecko.com/api/v3/coins/list)

**Comment by cerberus-zone** [comment]
@JeremyParish69 we have put liquidity in the pool yesterday, and it was drained in 45 minutes. Are bots draining the pool, before it has launched?

See the image links of the decrease in the pool liquidity in about 1 hour.

Initial Liquidity - https://cerberus-chain.s3.us-east-2.amazonaws.com/main/1.png
Liquidity after 20 minutes - https://cerberus-chain.s3.us-east-2.amazonaws.com/main/2.png
Liquidity now - https://cerberus-chain.s3.us-east-2.amazonaws.com/main/3.png

Can you help us figure out why our pool liquidity is being drained before we put more cash into it?

Thanks for any assistance you can give.

**Comment by RoboMcGobo** [comment]
> @JeremyParish69 we have put liquidity in the pool yesterday, and it was drained in 45 minutes. Are bots draining the pool, before it has launched?
> 
> See the image links of the decrease in the pool liquidity in about 1 hour.
> 
> Initial Liquidity - https://cerberus-chain.s3.us-east-2.amazonaws.com/main/1.png Liquidity after 20 minutes - https://cerberus-chain.s3.us-east-2.amazonaws.com/main/2.png Liquidity now - https://cerberus-chain.s3.us-east-2.amazonaws.com/main/3.png
> 
> Can you help us figure out why our pool liquidity is being drained before we put more cash into it?
> 
> Thanks for any assistance you can give.

The pool isn't being "drained," per se. People are selling their airdrops into the pool (note how the number of CRBRUS tokens are actually increasing). This drives the price down so the total liquidity's USD value is decreasing. Every pool you have created is live on Osmosis and anyone with access to Osmosisd via CLI can swap tokens in those pools.

**Comment by JeremyParish69** [comment]
@cerberus-zone 

First, note that because the CRBRUS price oracle isn't functioning yet, so the CRBRUS side of the pool is not being included in the total.

Also, @RoboMcGobo is correct. There is no way others can drain your liquidity. Based on the circulating supply and how the pool has flooded with CRBRUS tokens, it seems that the pool creator may have massively overestimated the value of a CRBRUS token by 72 times. Had the pool started with a fair balance, there would have been no decrease to the HUAHUA side.

From here, you could try adding more liquidity at this new ratio (would need about 15 Billion tokens to bring it up to $1000 liquidity). Alternatively, you could try an LBP to allow the markets to discover the price organically without needing to provide too much  non-CRBRUS liquidity.

**Comment by cerberus-zone** [comment]
Ok, that makes sense. Should we wait to add more liquidity until it is ready to be listed on Osmosis? Since you all need it to show at least $1K of liquidity before listing, it continues to be traded, decreasing the liquidity.

Looks like @dylanschultzie has a few changes to be made to the code and update the PR.

Thanks for the help, and for explaining what was going on.

**Comment by JeremyParish69** [comment]
> Ok, that makes sense. Should we wait to add more liquidity until it is ready to be listed on Osmosis? Since you all need it to show at least $1K of liquidity before listing, it continues to be traded, decreasing the liquidity.
> 
> Looks like @dylanschultzie has a few changes to be made to the code and update the PR.
> 
> Thanks for the help, and for explaining what was going on.

Although merging the PR should wait for the price oracle to be corrected, you may still add liquidity before then.

**Comment by dylanschultzie** [comment]
> > _maybe_ added the pool price accurately?
> 
> If we are going to use pool 658, then we should try to add more liquidity first.
> 
> Also, please change: `spotPriceDestDenom: 'uhuahua',` to: `spotPriceDestDenom: DenomHelper.ibcDenom([{ portId: 'transfer', channelId: 'channel-113' }], 'uhuahua'),` we can see a similar notation for when ATOM was being used as the reference price.
> 
> and change: `destCoinId: 'chihuahua',` to: `destCoinId: 'chihuahua-token',` since chihuahua is some other token, while chihuahua-token is the coingecko id for huahua, as per the [CoinGecko coins list](https://api.coingecko.com/api/v3/coins/list)

Done 👍

**Review by JeremyParish69 — APPROVED** [review]

**Comment by cerberus-zone** [comment]
> @cerberus-zone
> 
> First, note that because the CRBRUS price oracle isn't functioning yet, the CRBRUS side of the pool is not being included in the total.
> 
> Also, @RoboMcGobo is correct. There is no way others can drain your liquidity. Based on the circulating supply and how the pool has flooded with CRBRUS tokens, it seems that the pool creator may have massively overestimated the value of a CRBRUS token by 72 times. Had the pool started with a fair balance, there would have been no decrease to the HUAHUA side.
> 
> From here, you could try adding more liquidity at this new ratio (would need about 15 Billion tokens to bring it up to $1000 liquidity). Alternatively, you could try an LBP to allow the markets to discover the price organically without needing to provide too much non-CRBRUS liquidity.

Ok, I will let the team know that the ratio was off when creating the pool by 72 times. We also have an LBP setup too and may use that one. Definitely, don't have 15 billion tokens :)

**Pull request merged**
