### PR TITLE
Add functionality to support toggling of zero balances showing up in the asset list

### PR DESCRIPTION
**Pull request by Njerschow**
Add a button to toggle showing and hiding coins with 0 balance:

Toggled:
image

Untoggled:
image

### CODE REVIEW

**Comment by jonator** [comment]
@victortokaito thoughts on design?

**Comment by Miniminitrue** [comment]
> @victortokaito thoughts on design?

Make it a symbol to save space (eye open/closed for example).

**Comment by jonator** [comment]
@Miniminitrue for the refactor we include this functionality. We use a simple check box to implement this.

This may not be merged since we are very close to completing the refactor.

**Comment by dylanschultzie** [comment]
This is great, looking forward to this.

**Comment by Njerschow** [comment]
@jonator shall I close this then? would love to see it merged asap - I can add eye open/closed instead of button if it means it will be merged.

**Comment by victortokaito** [comment]
Because the suggested change uses a button design, it becomes the dominant call-to-action here (draws more attention than the deposit/withdraw actions). We'd also have to consider how it is positioned relative to the "search" and "sort by" features. I'd like to revisit this as I think this may be a nice place to consider adding a general deposit button as we've discussed briefly.

> Make it a symbol to save space (eye open/closed for example).

This would be nice to have just an icon, but it may not be immediately apparent what is being toggled to appear/disappear. I would suggest an accompanying text description to join the icon, but this will take up as much room as what we have implemented now. 

Screen Shot 2022-05-10 at 1 45 37 PM

**Comment by victortokaito** [comment]
Also, keep in mind how this might work on the mobile version.

**Comment by ankurdotb** [comment]
> Because the suggested change uses a button design, it becomes the dominant call-to-action here (draws more attention than the deposit/withdraw actions). We'd also have to consider how it is positioned relative to the "search" and "sort by" features.

I agree with the sentiment here. Can I suggest maybe using a "[slider toggle](https://v5.material.angular.io/components/slide-toggle/overview)" (the linked example is Angular, but I wanted to just illustrate a point) as that gives a clean and compact way of toggling zero balance displays on/off vs having a button.

**Comment by victortokaito** [comment]
Hi ankurdotb, thanks for bringing this up.

We have a slider toggle implemented on the mobile version of the UI update. For mobile, we wanted to make use of the perceived swiping affordance, but went this route on the desktop version to introduce fewer UI components (the checkbox is used in several other areas). 

@jonator, I can see how changing "hide zero balances" to a slider toggle could help bring the mobile more closely in line with the desktop. Side note: Switches and checkboxes are both used to enable settings. But the immediacy of when users expect those settings to activate are different. And the slider toggle has more of an instantaneous feeling.

**Comment by ankurdotb** [comment]
> And the slider toggle has more of an instantaneous feeling.

Yes, I agree with you on this. It has a more "instantaneous" feel like you said. I associate checkboxes with needing to click a button to "submit" and then carry out an action, since checkboxes are more common in forms where a box might be ticked / unticked without any action happening until an explicit accept/submit is done.

But these are minor differences really. 

The other switch I'd do is bump the checkbox or slider to the top, so that it's above the fold/doesn't require me to scroll too much to get to it.

**Comment by jonator** [comment]
https://refactor.osmosis.zone

**Pull request closed without merging**
