### PR TITLE
Add IST

### PR DESCRIPTION
**Pull request by zmanian**

### CODE REVIEW

**Review by JeremyParish69 — CHANGES_REQUESTED** [review]
Not sure that we can put 'isVerified'.

Otherwise, it LGTM. The chain-infos data and img were already uploaded, so this should suffice. Price is still undefined, but that's OK for now.

**Comment by zmanian** [comment]
Why would BLD be verified and IST not be verified?

**Comment by jonator** [comment]
That's our way of marking incentivized/strategic assets to be included in the main app vs frontier.

**Comment by zmanian** [comment]
Changed

Are we good to merge?

the Decentralized Cooperation Foundation is planning incentivize the IST pools asap.

**Pull request merged**
