### PR TITLE
(Wallet Addition) Add Galaxy Station wallet

### PR DESCRIPTION
**Pull request by echel0n-HX**
## What is the purpose of the change:

Include Galaxy Station Cosmos-Kit wallet

### CODE REVIEW

**Review by DavideSegullo — APPROVED** [review]

**Comment by CryptoAssassin1** [comment]
I enough Osmo in my wallet for the tx but wallet is not selecting Osmo and also Osmo is not included in the gas token list.
https://github.com/osmosis-labs/osmosis-frontend/assets/103904125/8e315734-5846-4eea-ad09-775cda85f680

**Comment by kamal-sutra** [comment]
@echel0n-HX sometimes the networks are disabled and deposit/withdraw doesn't pop up the tx window.
[Screencast from 25-06-24 01:10:56 PM IST.webm](https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/91615f45-80d3-457d-8e84-2a9a3cf0dc44)

**Comment by CryptoAssassin1** [comment]
@echel0n-HX this is my Osmosis address but as you can see in the video above Osmo is not included in the gas fee token list
osmo1qnqzdknfvr97uswyvr5qcehmlxhja92zq74dz5

**Comment by echel0n-HX** [comment]
@kamal-sutra I've updated the LCD endpoint for Sentinel and performed a Osmosis -> Sentinel swap
https://www.mintscan.io/osmosis/tx/928A20D3833E3794480A429C84F0C45692E567A5E55D13F112F4A8A4480A192D

**Comment by CryptoAssassin1** [comment]
@echel0n-HX check again and still same issue 
https://github.com/osmosis-labs/osmosis-frontend/assets/103904125/020e05a3-b931-41bd-8cd9-dfc224749e91

**Comment by echel0n-HX** [comment]
@CryptoAssassin1 what dev env are you testing this from, I'm currently using Win 11 and Edge with Galaxy Station Wallet v1.0.51

**Comment by echel0n-HX** [comment]
Osmo -> Tia
https://www.mintscan.io/osmosis/tx/8F197DBD75406441EF0675AC2DFDCD9B1B1E59CF63091F4DA0A69B4F310708C8

Tia -> Osmo
https://www.mintscan.io/osmosis/tx/C64B9260084C5900A4B26E59A1B57E443FC5B43203F8ADE8E36C949FC3F82E05

**Comment by CryptoAssassin1** [comment]
@echel0n-HX im using Ubuntu 22.04.1 LTS and extension version 1.0.51

**Comment by echel0n-HX** [comment]
@CryptoAssassin1 I've messaged you on Discord, I believe the issue may be related to Chrome browser

**Comment by kamal-sutra** [comment]
@echel0n-HX 
1. When Max Osmo is selected to swap, it is not deducting gas fee automatically. Need to manually input Max minus gas amount.
2. When there is 0 Osmo balance, the wallet is not switching to other available whitelisted fee tokens like atom/tia/usdc etc..

**Comment by CryptoAssassin1** [comment]
@echel0n-HX i dont think its OS and browser issue.
The issue is related to wallet.

**Comment by echel0n-HX** [comment]
@kamal-sutra thanks for that info, I am now able to reproduce @CryptoAssassin1 issue and am working to resolve it.

**Comment by echel0n-HX** [comment]
@kamal-sutra I removed the `preferNoSetFee` sign option, please authorize Vercel and lets see if that resolves the fee issues.

**Comment by MaxMillington** [comment]
@CryptoAssassin1 @kamal-sutra deploy authorized

**Comment by echel0n-HX** [comment]
@CryptoAssassin1 @kamal-sutra so after extensive debugging, what I have determined is that osmosis zone app is posting a request to Galaxy Station extension with the wrong denom, its using `ibc/0EF15DF2F02480ADE0BB6E85D9EBB5DAEA2836D3860E9F97F9AADE4F57A31AA0`, when it should be using `uosmo`

Its not cosmos-kit issue either, as we have tested on another app that uses cosmos-kit to swap whale -> to osmosis and logged the posted request, the proper denom of `uosmo` was present.

Any ideas ?

**Comment by MaxMillington** [comment]
> @CryptoAssassin1 @kamal-sutra so after extensive debugging, what I have determined is that osmosis zone app is posting a request to Galaxy Station extension with the wrong denom, its using `ibc/0EF15DF2F02480ADE0BB6E85D9EBB5DAEA2836D3860E9F97F9AADE4F57A31AA0`, when it should be using `uosmo`
> 
> Its not cosmos-kit issue either, as we have tested on another app that uses cosmos-kit to swap whale -> to osmosis and logged the posted request, the proper denom of `uosmo` was present.
> 
> I should also note that I did try whale -> osmosis as well on the latest osmosis zone preview, same issue with the wrong denom.
> 
> Any ideas ?

@JoseRFelix perhaps you have some context here?

**Comment by echel0n-HX** [comment]
@kamal-sutra regarding the gas fee issues, it seems this was brought up before when Terra Station was added and it was determined the issue to be on the side of osmosis app possibly, please see previous thread regarding this https://github.com/osmosis-labs/osmosis-frontend/pull/2210#issuecomment-1886867424

**Comment by echel0n-HX** [comment]
what next steps are required to get this moving forward ?

the gas fee denom issue doesn't look like its something on our side that is fixable, as long as there is osmo in the end-users wallet, tx's go through fine.

**Comment by jonator** [comment]
@echel0n-HX does galaxy station accept alternative fee tokens? Our FE suggests alternative tokens to pay fees depending on the user's balance

**Comment by echel0n-HX** [comment]
@jonator based on the gas fee denom passed in via the TX request, and if there is not enough of it to cover the gas, galaxy station will provide the end-user the ability to swap other coins using swap.io to get the required amount of said gas fee denom.

so in the case of the gas denom required being osmo, then osmo needs to be sent as the gas fee denom in the TX request, if there is not enough osmo in the end-users wallet, they will be able to swap other tokens to get more osmo, such as swapping whale -> osmo or chihuahua -> osmo.

the problem right now with trying to swap lunc through swap.io is that there are no routes for it, and its an issue that swap.io is looking into still on their end.

is there a way to have osmosis frontend pass in osmo instead of passing in alternative fee tokens based on balance specifically for galaxy station ? also, this same issue plagues terra station.

**Comment by echel0n-HX** [comment]
@jonator another idea would be to implement a dropdown to allow the end-user to select the gas denom they wish to use for the fee, that will then be passed on in the TX request to the connected wallet, sort that dropdown by balance as well

**Comment by echel0n-HX** [comment]
@jonator I see PR https://github.com/osmosis-labs/osmosis-frontend/pull/3423 has been created to address the alt fee issue, this PR should resolve the fee issues we are seeing with Galaxy Station, is there a time frame for when that PR will be merged so we can update our PR as well ?

Thanks!

**Comment by jonator** [comment]
stale

**Pull request closed without merging**
