### PR TITLE
Publish Stage

### LINKED ISSUE #1194: Swap tool: enter key not selecting asset
It seems like the enter key no longer works for selecting tokens in the drawer.

https://user-images.githubusercontent.com/4606373/210941309-af41f663-2ac2-41a5-88eb-b80cc91ef1a7.mov

### PR DESCRIPTION
**Pull request by jonator**
* Add button variants
* Fixes #1194 
* Add icon button

### CODE REVIEW

**Comment by jonator** [comment]
@arispech tokens should appear now, new pools query endpoint inherited from master

**Comment by jonator** [comment]
@arispech this release is smaller, but ready

**Review by arispech — APPROVED** [review]
Tested on the front-end and working as expected

**Review by sunnya97 — APPROVED** [review]

**Comment by sunnya97** [comment]
utAck

**Pull request merged**
