### PR TITLE
feat: Upgrade Cosmos Kit

### PR DESCRIPTION
**Pull request by JoseRFelix**
## What is the purpose of the change

Upgrade cosmos-kit to enable Wallet iframe pass-through wallets. 

## Brief Changelog

- Upgrade cosmos-kit and wallets
- Upgrade chain registry

## Testing and Verification

We should test all available wallets

- [ ] Allows connecting to wallets and persists sessions
- [ ] Allows sending transactions
- [ ] Allows signing for notifications
- [ ] Images should load on the profile

### CODE REVIEW

**Comment by NoahSaso** [comment]
Hey, you can test whether or not this is working at this link:

https://dapp-mainnet-git-noah-fullscreen-browser-da0da0.vercel.app/dao/osmo1xxf82kcpjkmsua9r5hvh6nwmg5s0pmp2u77xnczc6yqy8uztp4xspcn6t6/apps?url=https%3A%2F%2Fosmosis-frontend-git-jose-upgrade-cosmos-kit-osmo-labs.vercel.app%2F

This is our preview branch using your preview branch URL 😁 it seems to be causing some client-side error still.

**Comment by JoseRFelix** [comment]
@NoahSaso Thank you! This will make it much easier to debug.

**Comment by NoahSaso** [comment]
> @NoahSaso Thank you! This will make it much easier to debug. 

No problem :) stoked you are on top of this so quickly 🤝

Also, you should be able to use http://localhost:3000 in that URL field for real time development.

**Comment by JoseRFelix** [comment]
It appears that there have been breaking changes from Cosmos-Kit, making this more than the simple bump I anticipated. Due to urgent development tasks, I must delay addressing this until I have more availability. However, if you have the capacity, I'm certainly willing to assist you in completing this task.

**Comment by NoahSaso** [comment]
> It appears that there have been breaking changes from Cosmos-Kit, making this more than the simple bump I anticipated. Due to urgent development tasks, I must delay addressing this until I have more availability. However, if you have the capacity, I'm certainly willing to assist you in completing this task.

Gotchu.

**Comment by NoahSaso** [comment]
> It appears that there have been breaking changes from Cosmos-Kit, making this more than the simple bump I anticipated. Due to urgent development tasks, I must delay addressing this until I have more availability. However, if you have the capacity, I'm certainly willing to assist you in completing this task.

Can you point me to the breaking changes? It seems to build fine.

**Comment by NoahSaso** [comment]
@JoseRFelix the iframe wallet seems to work after this fix: #2552

**Review by jonator — APPROVED** [review]

**Review by arispech — APPROVED** [review]
Look good!
 :white_check_mark:Allows connecting to wallets and persists sessions
 :white_check_mark:Allows sending transactions
 :white_check_mark:Allows signing for notifications
 :white_check_mark:Images should load on the profil

**Pull request merged**
