### PR TITLE
Update learn more copy & animations

### PR DESCRIPTION
**Pull request by jonator**
### ClickUp Task

[ClickUp Task URL](PASTE_CLICKUP_TASK_URL_HERE)

### CODE REVIEW

**Comment by sunnya97** [comment]
I think Syed / the animator will have new copy / animations very soon.  Let's wait for that

**Comment by jonator** [comment]
> I think Syed / the animator will have new copy / animations very soon. Let's wait for that

Yep I just have step 1 so far

**Comment by sunnya97** [comment]
@jonator do you know how to make the lottie animations restart from the beginning every time they come you come to their page?  It feels like they start from a random time (but that might be because they all are running even when they're hidden)

**Comment by sunnya97** [comment]
Merging this and creating a new issue for restarting animations

**Pull request merged**
