### PR TITLE
Announcement Banner: Frontier Decommissioning (to master) 

### PR DESCRIPTION
**Pull request by JeremyParish69**
## What is the purpose of the change

Adds the Frontier decom notice banner (removes the levana banner)
Replaces the Levana bg back to the Supercharged Liquidity bg

## Brief Changelog

-frontier banner key in feature flag,
-update all banner description localizations to new message
-set bg to Supercharge Wosmo
-delete the levana bg images

## Testing and Verifying

This change has been tested locally by rebuilding the website and verified content and links are expected

### CODE REVIEW

**Comment by jonator** [comment]
noticed this locally as well

**Comment by daniel-farina** [comment]
Ok, we can merge once approved by devs 👍

**Comment by MaxMillington** [comment]
@daniel-farina @JeremyParish69 Can we just merge this to stage and the immediately do a release?

**Comment by JeremyParish69** [comment]
> @daniel-farina @JeremyParish69 Can we just merge this to stage and the immediately do a release?

I don't see why not. It's mostly already on stage, but stage still has the broken low res image reference. Merging this to stage should fix that.

**Review by jonator — APPROVED** [review]

**Comment by daniel-farina** [comment]
@MaxMillington  we wanted to avoid stage while it's being fixed with all the branch issues we had 👍  Let's merge this maybe tomorrow at 10AM ET and I can then enable the redirection rule.   Waiting for your final approval @MaxMillington  👍

**Pull request merged**
