### PR TITLE
feat: Add Support to Navigation Sidebar

### PR DESCRIPTION
**Pull request by JoseRFelix**

### CODE REVIEW

**Review by jonator — CHANGES_REQUESTED** [review]
Hey I diff'd the en.json with a few other .json lang files, it appears the localizations aren't synced. Can you please fix those? Thanks 🙏

**Comment by JoseRFelix** [comment]
@jonator Sure! Did you diff them from this branch?

**Comment by jonator** [comment]
> @jonator Sure! Did you diff them from this branch?

Yes

**Comment by JoseRFelix** [comment]
@jonator Sorted alphabetically and synced the JSON files. It's ready for a re-review

**Review by jonator — APPROVED** [review]

**Pull request merged**
