### PR TITLE
Add Connect to leap mobile using WalletConnect v2

### PR DESCRIPTION
**Pull request by baryon2**
## What is the purpose of the change

This PR adds the option to connect to Leap Mobile app from desktop/mobile browsers using WalletConnectV2.  

## Brief Changelog
Adds option for Leap Mobile in Mobile Wallets section on the Connect wallet modal.

Screenshot 2023-12-20 at 4 47 11 PM

## Testing and Verifying

This change has been tested locally by rebuilding the website.

https://github.com/osmosis-labs/osmosis-frontend/assets/97340331/71a58dd5-38c6-4ee2-bfd8-b8dd093125b0

### CODE REVIEW

**Review by kamal-sutra — APPROVED** [review]
Connects well on both pc and mobile app

**Review by arispech — APPROVED** [review]

**Comment by CryptoAssassin1** [comment]
Worked fine closing just X button is hiding on mobile
image

**Comment by sunnya97** [comment]
@CryptoAssassin1 I assume that's probably not because of their PR, but because we need to fix a layout issue on our own modal.  Can you create a separate bug report for this?

**Comment by sunnya97** [comment]
@baryon2 will you guys have a way of making the supported chain ids more scalable, so we don't have to keep updating this list everytime a new chain is added?

**Comment by baryon2** [comment]
> @baryon2 will you guys have a way of making the supported chain ids more scalable, so we don't have to keep updating this list everytime a new chain is added?

@sunnya97 Yes, we are planning to add support to fetch the list of supported chains ids from the wallet, once this is available you won't have to maintain this list on your end.

**Comment by CryptoAssassin1** [comment]
@sunnya97 done i created a clickup task.

**Review by JoseRFelix — APPROVED** [review]

**Pull request merged**
