### PR TITLE
github action

### PR DESCRIPTION
**Pull request by faddat**
This adds a basic github action to the front end repository so that teams making pull requests will get immediate feedback.

### CODE REVIEW

**Comment by faddat** [comment]
If we want to add anything else to this, please let me know. One thing that I realized from watching it run is that it’s looking for an osmosis instance on local host. We dealt with a lot of similar stuff while building blurt. I’m definitely interested in helping as much as I can to create an end and testing environment that can be reused with this and other front ends.

**Comment by jonator** [comment]
@faddat I'd reach out to @czarcas7ic who is currently working on setting up a test net.

**Comment by czarcas7ic** [comment]
This is a very interesting concept @faddat , I'm going to cc @daniel-farina as well since I know he would find this idea intriguing.

Only things that comes to my mind is the github action would also have to do the statesync workaround, in addition it feels like state sync is getting longer and longer (recently had one take up to an hour long). I think this might need its own investigating as well. Was going to reach out to you @faddat if you had any idea what could be going on since you said you had experienced something similar.

**Comment by faddat** [comment]
Hi guys, 

so, OMM has gotten things started with someone from Russia, who will host in Russia.

We are hoping to host from Vietnam, as well, both of these localized.  So right now I am making a docker-compose so that we can all work on the web front end more easily, and yep, it will state sync

**Comment by faddat** [comment]
Daniel,

You're right about state sync taking longer and longer, and I don't know why that is. I just found a little time now to work on the compose setup, I think this repo is the best place for it.

**Comment by czarcas7ic** [comment]
Since v7 happens tomorrow which breaks state sync, I kind of thought we would table it until the wasm fixes are implemented (unless you feel otherwise)

**Pull request closed without merging**
