### PR TITLE
move legacy pools query to local from edge

### PR DESCRIPTION
**Pull request by p0mvn**
## What is the purpose of the change:

Moves legacy pools query from edge to local

### CODE REVIEW

**Review by jonator — CHANGES_REQUESTED** [review]
Note this may still be in use by legacy mobx pool query stores (for individual pool vs all pools)

So we should remove all uses of those before we can merge this

https://github.com/osmosis-labs/osmosis-frontend/blob/683a00e7e6420e307af7d8dfaee1152a656c6aba/packages/stores/src/queries-external/pools/pool.ts#L340

**Comment by p0mvn** [comment]
I see - but we can probably move it to local from edge for now

**Comment by p0mvn** [comment]
@jonator restored query and moved to local from edge

**Review by jonator — CHANGES_REQUESTED** [review]
I don't believe this is going to move the runtime to the browser (as is possible with tRPC)

This config export is simply a config used by _Vercel_ to specify the runtime (serverless or edge) to be used when deploying this edge function. However, I'm not aware of Next.js supporting this feature as a way to move a query into browser. If so, that's news to me.

**Comment by p0mvn** [comment]
> I don't believe this is going to move the runtime to the browser (as is possible with tRPC)
> 
> This config export is simply a config used by _Vercel_ to specify the runtime (serverless or edge) to be used when deploying this edge function. However, I'm not aware of Next.js supporting this feature as a way to move a query into browser. If so, that's news to me.

I see - thanks for breaking it down. Let's then wait for portfolio v2 launch to remove the last use of it so that we can remove it in general

**Pull request closed without merging**
