### PR TITLE
Implement modal for Concentrated Liquidity Pool creation 

### PR DESCRIPTION
**Pull request by sunnya97**
### Linear Task

[Linear Task URL](PASTE_LINEAR_TASK_URL_HERE)

### CODE REVIEW

**Comment by sunnya97** [comment]
@fabryscript the second step isn't working for me – the add liquidity tx isn't loading

CleanShot 2024-07-10 at 17 24 27@2x

**Comment by fabryscript** [comment]
Hi @sunnya97! I checked again on testnet and it works like a charm

**Comment by sunnya97** [comment]
@fabryscript , @JohnnyWyles is still having the same issue as I did
CleanShot 2024-07-17 at 08 51 49

**Comment by JohnnyWyles** [comment]
image
This is the console error - integer used?

**Comment by fabryscript** [comment]
Should be fixed now, lmk! cc @sunnya97  @JohnnyWyles

**Comment by JohnnyWyles** [comment]
Pool created and initial liquidity added at 1:1.102 ratio using this flow!
A unique graphic for the CL pool icon would be great but otherwise working great!

There's the usual lag after pool creation where the frontend takes a few minutes to recognise a new pool, but that's an ongoing issue. May want to add some text that indicates that the liquidity hasn't just disappeared in this period.

**Pull request merged**
