### PR TITLE
feat: Use Commit Hash to Generate Asset Lists

### PR DESCRIPTION
**Pull request by JoseRFelix**
## What is the purpose of the change

Use commit hash to generate asset lists to avoid waiting for GitHub's CDN to refresh its cache.

## Testing

- [ ] Assets and chains should load like production

### CODE REVIEW

**Comment by sunnya97** [comment]
This can be done via url_param?

**Comment by JoseRFelix** [comment]
> This can be done via url_param?

This can't be done until we render the whole app through the server

**Review by jonator — APPROVED** [review]

**Comment by sunnya97** [comment]
We should probably have a test asset to check this with?

**Comment by kamal-sutra** [comment]
@JoseRFelix @JeremyParish69 Found only these differences. Rest all good. Please check/update.
image

**Pull request merged**
