### PR TITLE
Add STRDST

### PR DESCRIPTION
**Pull request by lakmalmabm**
This pull request is to add STRDST token on osmosis. 

- _Adds STRDST info to source-chain-infos.ts
- _Adds a token image to /tokens/strdst.svg

### CODE REVIEW

**Comment by lakmalmabm** [comment]
Hey @JeremyParish69 please let me if there is anything more I should do. 

thank you.

**Comment by JeremyParish69** [comment]
Hi, @lakmalmabm , is there a liquidity pool with this token? and what is the pool id # ?

**Comment by lakmalmabm** [comment]
Hey @JeremyParish69 , We are planing to use a stream swap so do we need to make the pool before it?

**Comment by JeremyParish69** [comment]
> Hey @JeremyParish69 , We are planing to use a stream swap so do we need to make the pool before it?

In that case, no, you don't. When is the StreamSwap panned for?

**Comment by lakmalmabm** [comment]
as soon as the Streamswap team processes our request, most probably within the next 2 weeks. 

currently, we are trying to move some testnet tokens from Stargaze testnet osmosis testnet. Once it is done, streamswap team will setup it using testnet tokens.

**Comment by lakmalmabm** [comment]
Hi @JeremyParish69 

We are going to start our streamswap session on 10/10 and once it is completed we need to create a pool. so can we continue on this PR.

**Pull request closed without merging**
