### PR TITLE
Upgrading Next from 12 to 13

### PR DESCRIPTION
**Pull request by DavideSegullo**
## What is the purpose of the change
It is a continuation of PR https://github.com/osmosis-labs/osmosis-frontend/pull/2232, on the previous branch I had made a mistake with the rebase and I didn't want to mess up the comment history

### CODE REVIEW

**Comment by JoseRFelix** [comment]
@DavideSegullo I just noticed that after the upgrade images are way bigger than in prod

Before:

image

After:

image

**Comment by DavideSegullo** [comment]
> @DavideSegullo I just noticed that after the upgrade images are bigger than in prod
> 
> Before:
> 
> image
> 
> After:
> 
> image

I'll give a look

**Comment by DavideSegullo** [comment]
> @DavideSegullo I just noticed that after the upgrade images are bigger than in prod
> 
> Before:
> 
> image
> 
> After:
> 
> image

I fixed this one, now I see if there are others, some I had already fixed, it happens because they changed the behavior of "next/image"

**Review by MaxMillington — APPROVED** [review]

**Comment by MaxMillington** [comment]
Approved the deploy. Let's make sure to have QA take a look before merging

**Comment by DavideSegullo** [comment]
> @DavideSegullo if you rebase and fix the conflicts, I can approve the deploys and we can hopefully get this merged this week! A huge help!

Done

**Review by JoseRFelix — APPROVED** [review]
LGTM!

**Pull request merged**
