### PR TITLE
Fix/ Automatically deduct fees when swapping with MAX ##2518

### PR DESCRIPTION
**Pull request by HarjobandeepSingh**
## What is the purpose of the change

This pull request aims to fix the issue where fees are not automatically deducted when a user selects the 'MAX' option during asset swapping.

## Brief Changelog

- Modified the calculation of `osmoOutAmount` in `add-liquidity.ts` to always deduct the `OSMO_MEDIUM_TX_FEE` from the balance before comparing it with the out amount.

## Testing and Verifying

This change has been tested locally by running the asset swapping functionality and verifying that the fee is correctly deducted when the 'MAX' option is selected.

## Documentation and Release Note

- This pull request introduces a change in the user-facing behavior. Previously, fees were not deducted when the 'MAX' option was selected during asset swapping. With this change, the fee will be automatically deducted.

### CODE REVIEW

**Comment by HarjobandeepSingh** [comment]
fix/ #2518

**Comment by MaxMillington** [comment]
@HarjobandeepSingh looks like the build is failing here due to a syntax error? Are you able to build this locally?

**Review by jonator — CHANGES_REQUESTED** [review]
This appears to be making changes to the add liquidity state, and not swapping?

**Comment by HarjobandeepSingh** [comment]
> This appears to be making changes to the add liquidity state, and not swapping?

@jonator check again plz

**Comment by HarjobandeepSingh** [comment]
@MaxMillington sir plz check now

**Comment by HarjobandeepSingh** [comment]
@jonator plz check

**Comment by jonator** [comment]
@HarjobandeepSingh this is not close. Swap modal changes would likely be in `useSwap` hook. And would only apply if it's the staking currency

**Pull request closed without merging**
