### PR TITLE
Filter by token for pools

### LINKED ISSUE #169: Put pools that a token is in on its page
For example, at https://info.osmosis.zone/token/OSMO, have all the pools with OSMO. Ill try to do this later

### PR DESCRIPTION
**Pull request by jimbarrey**
Initial idea to fix #169 

will show all UST based pools at /pools/ust

image

### CODE REVIEW

**Comment by jonator** [comment]
We're currently looking at mockups to integrate this in the UI. We will add filtering functionality once we complete a refactor. Thanks!

**Comment by jonator** [comment]
Update: in the refactor we're going to be using an input box to allow users to instantly filter pools + assets on more than just token denom. Feel free to revisit this post refactor if you still believe it would be useful! The refactor also introduces next.js and it's own approach to routing. Thanks!

**Comment by jonator** [comment]
👀 Preview: 

Screen Shot 2022-03-03 at 10 08 10 AM

**Comment by jimbarrey** [comment]
@jonator Looks great!

**Pull request closed without merging**
