### PR TITLE
Publish Stage

### LINKED ISSUE #920: Bridge Integration: auto-wrap native assets
### Background
WETH is simply an ERC20 1:1 version of native ETH, which is treated differently on Ethereum. It allows products that depend on the ERC20 standard to work with ETH as well. In this case, the product is Axelar’s gateway contract. It is somewhat a pitfall of the EVM design.

### Proposed solution 
For our WETH integration, we should support the option for users to deposit native ETH.

Since Axelar is adding [support](https://osmosis-network.slack.com/archives/C028SRRL4LX/p1666405744118759) themselves, we'd just need to update our querying and add UI to let the user switch to ETH from WETH. Then we'd send Eth to the generated address, instead of an ERC20 transfer.

### LINKED ISSUE #1349: Enable `react-hooks/exhaustive-deps` eslint rule
The `react-hooks/exhaustive-deps` eslint rule should be enabled to ensure hooks have all required dependencies.
This will require applying the rule to all files and commenting in situations where exhasutive dependencies are not required (e.g. `all-pools-table`.

### LINKED ISSUE #1388: stATOM deeplink not working
Deeplinking to ATOM/stATOM doesn't work https://app.osmosis.zone/?from=ATOM&to=stATOM 

(only if you have app.osmosis.zone open and change the URL)

### LINKED ISSUE #1390: Add `Support` Menu Item to Sidebar
image

### LINKED ISSUE #1393: Frontier ?from=OSMO&to=MEME not working
I think when inputting MEME in the url for example https://frontier.osmosis.zone/?from=OSMO&to=MEME and hitting enter the url automatically changes to https://frontier.osmosis.zone/?from=OSMO&to=OSMO that is why the UI broke?
Screen Shot 2023-03-16 at 1 22 26 PM

### PR DESCRIPTION
**Pull request by jonator**
* Closes #920 
* Swap Tool: Limit available balance to 8 decimals. Closes https://github.com/osmosis-labs/osmosis-frontend/issues/1346
* LayerSwap: use Coinbase to deposit USDC instead of Kado 
* **New Pools Page!** includes infinite scroll. Closes #1349 #1248 #1175 #1057
* Closes #1388 Closes #1393
* Closes #1390
 

### Testing
* Axelar deposit/withdraw ETH, GLMR, AVAX, MATIC, FTM, BNB
  * Depositing: since these are gas tokens being transferred, make sure the gas cost is calculated and properly deducted from the transfer amount when clicking max. Make sure there's enough gas to click confirm, to prevent metamask from blocking us since it claims we don't have enough gas token to pay gas fees.
* Axelar deposit withdraw non-wrapped asset
* Connecting/disconnecting Metamask
* Ensure links to satellite work properly; for deposit/withdraw, and the proper assets/networks are present on satellite
* Only show swap route vis in home page, not in pool detail page
* Deposit USDC from Coinbase via LayerSwap
* statom deeplink

### CODE REVIEW

**Comment by arispech** [comment]
*----------------------------------------WIP-----------------------------------*

### Testing
- [x] Auto-wrap native assets 

### Axelar deposit/withdraw non-wrapped asset

- ETH 
- [ ] deposit***** issue being track
- [x] withdraw
- GLMR
- [ ] deposit
- [ ] withdraw
- AVAX
- [x] deposit
- [x] withdraw 
- MATIC
- [x] deposit
- [x] withdraw 
- FTM
- [x] deposit
- [x] withdraw
- BNB 
- [ ] deposit *****  issue being track
- [x] withdraw

###  Depositing: since these are gas tokens being transferred
- [x] make sure the gas cost is calculated and properly deducted from the transfer amount when clicking max. 
- [x] Make sure there's enough gas to click confirm, to prevent metamask from blocking us since it claims we don't have enough gas token to pay gas fees.

- [x] Connecting/disconnecting Metamask
- [x] Ensure links to satellite work properly; for deposit/withdraw, and the proper assets/networks are present on satellite
- [x] Only show swap route vis in home page, not in pool detail page
- [x] Swap Tool: Limit available balance to 8 decimals. Closes https://github.com/osmosis-labs/osmosis-frontend/issues/1346

- [x] Deposit USDC from Coinbase via LayerSwap

### New Pools Page 
- [x] [Incorrect APR sorting #1248](https://github.com/osmosis-labs/osmosis-frontend/issues/1248) 
- [x] [Redesign pools page #1175](https://github.com/osmosis-labs/osmosis-frontend/issues/1175) infinite scroll
- [x] [Pools Tabs shouldn't stay in 0. #1057](https://github.com/osmosis-labs/osmosis-frontend/issues/1057)

**Review by arispech — APPROVED** [review]
The front-end is looking good!

**Review by JeremyParish69 — APPROVED** [review]
Config code looks correct. 
-no longer refers users to external wrapping interfaces (probably a good call)
-does appear to remove the 'w' on tokens wrapped my its own mother chain (yay!)
-seems to retain the gas config changes

**Review by daniel-farina — APPROVED** [review]
Ready for internal UAT!

**Pull request merged**
