### PR TITLE
Add Russian, `ru`

### PR DESCRIPTION
**Pull request by AzamatV4**

### CODE REVIEW

**Comment by AzamatV4** [comment]
Oh, sh...
Am I requesting to Master?
I only wanted to make it local, deny this request please
Sorry for such inconvenience, I am not familiar with how it works

**Comment by jonator** [comment]
Oh no worries. Thanks for this, long overdue!

**Comment by jonator** [comment]
Make sure you add it to the language selector

https://github.com/osmosis-labs/osmosis-frontend/blob/1f3cad0fb7e7f015ea70915bb9bc1551b9f05fa9/packages/web/stores/user-settings/language.tsx#L13

**Comment by jonator** [comment]
Also, I've noticed much of the file is missing the translations

**Pull request closed without merging**
