### PR TITLE
feat: Cosmostation mobile

### PR DESCRIPTION
**Pull request by G-Gamja**
We have resolved the Node.js version issue from the [previous PR](https://github.com/osmosis-labs/osmosis-frontend/pull/3011) and submitted a new PR. Please review it.

## What is the purpose of the change:

support Cosmostation app wallet in Connect wallet popup component

### Linear Task

[previous PR](https://github.com/osmosis-labs/osmosis-frontend/pull/3011)

## Brief Changelog

- This supports connect Cosmostation app wallet feature

## Testing and Verifying

- This change has been tested locally by rebuilding the website with the Cosmostation app wallet (iOS and Android market versions).

### CODE REVIEW

**Comment by CryptoAssassin1** [comment]
@G-Gamja not seeing Cosmosation mobile option on mobile.
image

**Comment by CryptoAssassin1** [comment]
@G-Gamja not seeing Cosmostation option on mobile.
image

**Comment by G-Gamja** [comment]
@CryptoAssassin1 Thank you for reviewing this PR.

This PR includes the implementation that allows connecting the wallet within our app's WebView. We will also check if it is possible to connect the wallet in non-WebView environments using the WalletConnect feature.

**Comment by CryptoAssassin1** [comment]
@G-Gamja is it possible for us to test it?

**Comment by G-Gamja** [comment]
You can test by entering the local dev URL of the Osmosis front end in the Dev Mode under the Settings tab.

image

**Review by CryptoAssassin1 — APPROVED** [review]
Working fine.

**Review by kamal-sutra — APPROVED** [review]

**Review by jonator — APPROVED** [review]

**Pull request merged**
