### PR TITLE
Feat Reduce Text and Padding

### PR DESCRIPTION
**Pull request by JoseRFelix**

### CODE REVIEW

**Comment by syed8rahman** [comment]
Screen Shot 2022-12-05 at 4 42 18 PM
Bonded v Unbonded should expand vertically to fill container - same alignment as cards on either side.

**Comment by syed8rahman** [comment]
Screen Shot 2022-12-05 at 4 43 12 PM
Bond shares button is too wide, text shouldn't have to wrap to next line.

**Comment by JoseRFelix** [comment]
@syed8rahman Thanks for the feedback! I have applied them accordingly 👍

**Comment by syed8rahman** [comment]
Screen Shot 2022-12-07 at 2 26 56 PM

Made a few more adjustments.
1. Changed the # of shares from H6 to Subtitle 1 on both level 1 and level 2 (add liquidity step and bonding step)
2. Increased padding from 12px to 20px between the number of days and number of shares on the card.

Tagged these changes in comments of Pool Details Figma, also available in components in the design guidelines.

**Comment by syed8rahman** [comment]
Screen Shot 2022-12-07 at 2 31 46 PM
The balances should be aligned above the bar

**Comment by syed8rahman** [comment]
Screen Shot 2022-12-07 at 2 40 19 PM
Also made some adjustments to the details pop up. Figma screenshot below.
1. Changed percentage breakdown from H6 to Subtitle 1
2. Changed text colors - percentage is white, info on the right is osmoverse100
3. Adjusted tiny icons from 24px to 20px

Shown below 
Screen Shot 2022-12-07 at 2 41 54 PM

**Comment by syed8rahman** [comment]
Screen Shot 2022-12-07 at 2 45 30 PM
Adjusted the "Put your assets to work" subheader padding: 32px horizontal so it's aligned with all the other text elements

**Comment by syed8rahman** [comment]
Updates to the unbond button. Animation included can be viewed on a [prototype here.](https://www.figma.com/proto/7iWExDLY1u7kClXZwS3OZI/Pool-Details-%26-Modals?page-id=1%3A4&node-id=752%3A30967&viewport=1784%2C1406%2C0.17&scaling=min-zoom&starting-point-node-id=1297%3A76188)

And available in the design guidelines. Attached a screenshot below.

unbond

Screen Shot 2022-12-07 at 3 15 22 PM

**Comment by JoseRFelix** [comment]
@jonator Ready for review. Design feedback has been resolved

**Review by jonator — CHANGES_REQUESTED** [review]
Seems on tablet screen sizes, the pool composition dropdown height is not quite right. Both expanded and collapsed.
Screen Shot 2022-12-12 at 11 11 50 AM

**Comment by jonator** [comment]
Thoughts on retargeting the branch to master? We removed support for legacy.osmosis.zone due to incompatibility with v13 release, so it's especially important to release the user asset breakdown sooner than later.

**Comment by JoseRFelix** [comment]
We won't be able to given the asset breakdown feature is merged to the token select branch. This one only fixes some of its styles

**Pull request merged**
