### PR TITLE
fix the translation of "sharesAvailableIn"

### PR DESCRIPTION
**Pull request by yanglaolee**

### CODE REVIEW

**Comment by jonator** [comment]
We're about to include many more changes with v13 release. Mind if I let this set then you can merge from master and check the new translations as well?

**Comment by yanglaolee** [comment]
Sure, do it plz.

**Review by jonator — CHANGES_REQUESTED** [review]
@yanglaolee v13 is on master, feel free to update to your branch and include those changes.

**Comment by yanglaolee** [comment]
[jonator](https://github.com/jonator) Working on it, ser

**Comment by yanglaolee** [comment]
[jonator](https://github.com/jonator) We are ready to go, ser

**Review by jonator — APPROVED** [review]

**Pull request merged**
