### PR TITLE
feat: Transpile Modules in Next Dev Server and Add Lint to CI

### PR DESCRIPTION
**Pull request by JoseRFelix**
## What is the purpose of the change

Transpile local Osmosis modules using the Next.js configuration. Makes it easy to have local libraries and keep a slick, manageable dev experience. This will solve the issue with build collisions that required devs to clear the build folder on occasion. 

This PR also adds a Lint action that will improve the repo consistency, especially while merging asset PRs. 

### ClickUp Task

[Add Lint CI Action](https://app.clickup.com/t/866arqaqq)
[Transpile Next.js local Osmosis modules](https://app.clickup.com/t/866arqat3)

### CODE REVIEW

**Comment by jonator** [comment]
@JoseRFelix will try to look at this soon

**Review by jonator — APPROVED** [review]
Since we're touching our modules, can we also use this as an opportunity to update turbo repo in root package.json?
Screenshot 2023-08-10 at 10 10 38 AM

**Review by jonator — COMMENTED** [review]
Is the expected behavior to save a console log in the stores package, and the dev server would refresh automatically? I'm not able to get that to work

**Comment by JoseRFelix** [comment]
> Is the expected behavior to save a console log in the stores package, and the dev server would refresh automatically? I'm not able to get that to work

The server is updating and refreshing, but the client is not. I can see the changes through the console logs on the server, but these updates are not being reflected on the client. I think the class instances are not being updated maybe because of Mobx.

**Comment by jonator** [comment]
> > Is the expected behavior to save a console log in the stores package, and the dev server would refresh automatically? I'm not able to get that to work
> 
> The server is updating and refreshing, but the client is not. I can see the changes through the console logs on the server, but these updates are not being reflected on the client. I think the class instances are not being updated maybe because of Mobx.

Yeah that makes sense. The root store gets initialized once on load as a react context, and even if the source file gets updated in the browser, the root store data would not change.

**Comment by JoseRFelix** [comment]
> Yeah that makes sense. The root store gets initialized once on load as a react context, and even if the source file gets updated in the browser, the root store data would not change.

The issue is specific to Next.js v12. After extensive debugging, I found that upgrading to v13 will resolve the problem, as it automatically remounts the store whenever there's an update. I was able to reproduce this with their [example](https://github.com/vercel/next.js/tree/canary/examples/with-mobx) by downgrading it to v12

**Pull request merged**
