### PR TITLE
Revisit "My Pools" section in pools page

### PR DESCRIPTION
**Pull request by CMarshall92**
We've received a lot of feedback that it's confusing to see pools at the top of the assets page (as pool cards). We should revisit how we display owned pools (LP positions) in the assets page.

- [x] Move "My Pools" section (as it is) below assets table & IBC transfers table
image

- [x] Hide "My Pools" section when there are no pools to display
image

- [x] Move hide zero balances switch to left of search bar in assets table
Screenshot 2022-06-12 at 20 34 26

- [ ] Add link to support site

- [x] Add highly engaging link to frontier site (address concerns with finding non-scammy links)
Screenshot 2022-06-11 at 22 10 21

### CODE REVIEW

**Comment by jonator** [comment]
FYI it appears you've used npm to manage packages, seeing the package-lock.json. We use yarn and yarn lock to mange our packages.

**Comment by CMarshall92** [comment]
> FYI it appears you've used npm to manage packages, seeing the package-lock.json. We use yarn and yarn lock to mange our packages.

Yeah noticed that will update the branch and use yarn instead.

**Comment by CMarshall92** [comment]
The only point in this PR that im not 100% sure of is the support link, any suggestions on where that should navigate the user. I heard there isnt a web based support atm but its coming soon would it be better to direct the user towards discord?

**Comment by jonator** [comment]
@victortokaito @syed8rahman can we finalize the designs so @CMarshall92 can contribute? Thanks 🙏

**Comment by jonator** [comment]
Also, @CMarshall92 you may want to merge my work in `jonator/cosmetic2` so you can get the updates to the Hide zero balances component.

**Comment by CMarshall92** [comment]
@jonator I have merged your work into the branch im guessing its best to wait until that branch hits master before this branch can go from draft to official as there's now a load of changes that were not mine but you can see the updated UI on the staging env now.

**Comment by CMarshall92** [comment]
@victortokaito - just a quick one are you sure of removing the social links? heres what it looks with and without them on both mobile and desktop

WIth Social Links & Frontier Link
Desktop
Screenshot 2022-06-24 at 01 27 54
Mobile
Screenshot 2022-06-24 at 01 27 45

Without Social Links
Desktop
Screenshot 2022-06-24 at 01 29 17
Mobile
Screenshot 2022-06-24 at 01 29 24


Let me know and I can go from there, cheers for the update above

**Comment by CMarshall92** [comment]
I'm going to close this off as something odd has happened to the branch and there seems to be alot of changes that aren't mine.

A new PR has been raised 
https://github.com/osmosis-labs/osmosis-frontend/pull/653

Which brings the latest code changes in and implements the same changes

**Comment by victortokaito** [comment]
@CMarshall92 I agree I think it looks more well-balanced keeping the social links since this section has one color and looks centered. But I think our team has decided we want more space here in the sidebar. Do you all think we can shorten the copy for the support link to just "Get Support" or does that not reflect that it's DAO-maintained?

@jonator  @syed8rahman

**Pull request closed without merging**
