### PR TITLE
add Doga to frontend

### PR DESCRIPTION
**Pull request by dogeapr**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can you please define the price using a pool id?

**Comment by dogeapr** [comment]
Could you enable the IBC for me to transfer token to Osmosis?
@JeremyParish69

**Comment by JeremyParish69** [comment]
> Could you enable the IBC for me to transfer token to Osmosis? @JeremyParish69

IBC should already be enabled, but if you're asking for a preview link, there's one generated now.

**Comment by dogeapr** [comment]
@JeremyParish69  I updated, thank you

**Review by JeremyParish69 — APPROVED** [review]

**Pull request merged**
