### PR TITLE
Delete the "bootstrap" page endpoint, as its planned to be unused

### PR DESCRIPTION
**Pull request by ValarDragon**
## What is the purpose of the change

Deletes the LBP code ("/bootstrap") from the codebase, as its planned to be unused

### ClickUp Task

N/A

## Brief Changelog

Deletes the /bootstrap page.

## Testing and Verifying

This change has not been tested locally. Testing on stage links here

## Documentation and Release Note

We should have less to document. cc @JohnnyWyles if I'm missing anything in docs

### CODE REVIEW

**Comment by ValarDragon** [comment]
This looks correct to me, can you check @CryptoAssassin1 ?

**Comment by CryptoAssassin1** [comment]
@ValarDragon there is minor UI issue with Pool types and Incentives type drop down tick mark is dislocated and text is overlapping with checkbox im still testing it i will let you know when its done.

file:///home/assassin/Downloads/Screenshot%20from%202023-10-22%2015-31-59.png
Screenshot from 2023-10-22 15-26-14

**Comment by ValarDragon** [comment]
Oh wow, nice catch

**Comment by CryptoAssassin1** [comment]
@ValarDragon looking good didn't notice any change other then the above issue.

**Comment by ValarDragon** [comment]
@MaxMillington was saying he couldn't replicate when he builds locally. Should we merge, and then retry on stage, to see if it was some unrelated vercel issue?

**Comment by CryptoAssassin1** [comment]
@ValarDragon sure

**Review by jonator — APPROVED** [review]

**Pull request merged**
