### PR TITLE
Mobile UI - Assets, Pools, Pool Detail

### LINKED ISSUE #380: Mobile UI: Layout & foundation
To open up mobile dev, add mobile support for sidebar menu, header, all matching new mobile design.

### PR DESCRIPTION
**Pull request by jonator**
* Add hooks for window size and window scroll position
* Tweak overview component

Closes #380

### CODE REVIEW

**Comment by jonator** [comment]
Repurposing to close #368 (after merging #144), close #369, and ultimately close #346.

**Comment by jonator** [comment]
Update: due to @Thunnini working on trading functionality, this will exclude responsive UI for that functionality.

**Comment by jonator** [comment]
@delivan Feel free to review!

**Comment by delivan** [comment]
@jonator UX/UI Review:
- deposit/withdraw process needs to continue in one modal (no overlapping modal)
- "Hide zero balance" toggle button looks more big than the design
- sorting drop-down looks more big than the design
- Pool table item cannot be clicked(not be linked to pool detail page)
- padding values does not match the design of the pool detail page as a whole

**Comment by jonator** [comment]
@delivan ===> @victortokaito and I have discussed the button size issue, but otherwise the other issues are fixed

**Comment by jonator** [comment]
@delivan Ready for review.

**Comment by victortokaito** [comment]
(On desktop) If num of my pools is ≤ 6 in My Pools section, the show more button should not be shown.
(On mobile) If num of my pools is ≤ 3 in My Pools section, the show more button should not be shown.

**Comment by jonator** [comment]
@delivan @victortokaito I've updated from your feedback

**Review by delivan — COMMENTED** [review]
@jonator 
- When the connect wallet button is clicked on deposit/withdraw modal, the connect wallet modal is behind deposit/withdraw modal
- Still named as "Lab", not "Pool", in the Incentivized Pools section
- There is no feedback when the add token button is clicked on the create new pool modal

**Comment by jonator** [comment]
@delivan I've fixed the first bullet. For the second bullet I've created a bullet in issue #362 to fix all wallet connection logic together as I noticed "sign out" was not working either.

What do you mean on the last bullet? Like UI feedback? There is a gold outline that appears on focus

**Review by delivan — APPROVED** [review]

**Comment by delivan** [comment]
Oops, Never mind. I didn't connect wallet so nothing happened.
Now LGTM! Let's go further.

**Pull request merged**
