### PR TITLE
add Korean

### PR DESCRIPTION
**Pull request by gnujoow**
#919

I added a Korean translation, but it needs to be reviewed. Also, some translations need to be discussed. Can I discuss it with  @dogemos ?

for better review please check the link below
https://www.diffchecker.com/RuOJhW6f

### CODE REVIEW

**Comment by gnujoow** [comment]
@jonator I tried to see a preview on my machine but follow message showed up. Did I make any mistakes?
image

**Comment by jonator** [comment]
I think you need to run `yarn build` at least once before `yarn dev`.

**Comment by jonator** [comment]
Also be sure to re-merge the original branch and diff your file against `en.json`. I've changed/added some translations recently.

**Comment by gnujoow** [comment]
> I think you need to run `yarn build` at least once before `yarn dev`.

thank you. and i will check the original branch as well.

**Comment by gnujoow** [comment]
I will turn this pr to daft for now, and re-open it when it get done ;)

**Comment by jonator** [comment]
Wow, amazing. Thanks!

**Pull request merged**
