### PR TITLE
Update huahua gas

### PR DESCRIPTION
**Pull request by kamal-sutra**
### ClickUp Task

[ClickUp Task URL](PASTE_CLICKUP_TASK_URL_HERE)

### CODE REVIEW

**Comment by jonator** [comment]
Please fix merge confligts

**Comment by JeremyParish69** [comment]
The [Chain Registry](https://github.com/cosmos/chain-registry/blob/a8c93284ec16ae8b6f69b32c531ee8b26a02d22d/chihuahua/chain.json#L17) has 1, 5, 10, and the [Keplr Chain Registry](https://github.com/chainapsis/keplr-chain-registry/blob/6db1a67b377562adf435aa6b9c3d005144962bec/cosmos/chihuahua.json#L41) has 100, 250, and 500.
Although this likely works, where do the numbers 100, 200, 300 come from?

**Comment by kamal-sutra** [comment]
Thanks for the references. Updated according to Keplr registry.

**Comment by JeremyParish69** [comment]
Thanks for the changes. Looks like there are still merge conflicts, tho. Could you please resolve, @kamal-sutra ?

**Pull request closed without merging**
