### PR TITLE
Update new pools table

### PR DESCRIPTION
**Pull request by jonator**
### ClickUp Task

[ClickUp Task URL](https://app.clickup.com/t/86a1uagzk)

## Brief Changelog

* Update global pool CSS, for consistency of pool table UI across app

### CODE REVIEW

**Comment by jonator** [comment]
This branch also has OOM build issues. Once https://github.com/osmosis-labs/osmosis-frontend/pull/2701 is merged I will merge stage into this branch and builds should work.

**Comment by sunnya97** [comment]
The loading icon became left aligned
CleanShot 2024-01-18 at 15 00 46@2x

**Comment by jonator** [comment]
@sunnya97 fixed spinner

**Review by CryptoAssassin1 — APPROVED** [review]

**Comment by CryptoAssassin1** [comment]
Volume and search overlapping on resolution 1025px to 1107px
Screenshot from 2024-01-19 22-46-16

**Review by CryptoAssassin1 — APPROVED** [review]

**Review by kamal-sutra — APPROVED** [review]

**Pull request merged**
