### PR TITLE
stage to master

### PR DESCRIPTION
**Pull request by sunnya97**
### ClickUp Task

[ClickUp Task URL](PASTE_CLICKUP_TASK_URL_HERE)

### CODE REVIEW

**Review by DavideSegullo — APPROVED** [review]

**Review by MaxMillington — APPROVED** [review]

**Comment by jonator** [comment]
I think https://github.com/osmosis-labs/osmosis-frontend/pull/2666 is causing issues with build container running out of memory, due to generation of one HTML file per pool. Still investigating.

**Review by jonator — CHANGES_REQUESTED** [review]
Investigating OOM build error in https://github.com/osmosis-labs/osmosis-frontend/pull/2666

**Comment by jonator** [comment]
OOM fix is in https://github.com/osmosis-labs/osmosis-frontend/pull/2701

**Comment by sunnya97** [comment]
This stage seems to be getting pretty big.  Let's merge?

**Pull request merged**
