### PR TITLE
chore: Updated gauges for CHEQ pool 602 and 617

### PR DESCRIPTION
**Pull request by ankurdotb**
Minor change to update gauges for pools 602 and 617 to the latest ones. At the time of creating this PR, there were no merge commit conflicts.

### CODE REVIEW

**Comment by ankurdotb** [comment]
@JeremyParish69 Whoops I see a deploy failing. Please let me know if there's something wrong with this PR or a anything else I can do to help resolve.

**Comment by JeremyParish69** [comment]
> @JeremyParish69 Whoops I see a deploy failing. Please let me know if there's something wrong with this PR or anything else I can do to help resolve it.
> 
> (PS - I targetted `master` since we're on the main app, but let me know if there's a preference to target `frontier` first now, and then there's some kind of auto-promote to `master` in Vercel.)

Thanks! The deployment (which I should never have triggered) failed because it was trying to deploy conflicting code--a 'master' PR to a 'frontier' environment.

The code changes look good to me, so I've copied the changes over to another PR #478 , which has been tested with success. It would actually be better for this to point to Frontier so we can keep both environments in sync.

**Comment by ankurdotb** [comment]
@JeremyParish69 I'm a bit confused...should I retarget this PR for Frontier? Since you already created the other PR, I'm not sure whether this is needed any more?

Also, if a token is in the main app like ours, am I not supposed to send PRs targeting master any more?

**Comment by JeremyParish69** [comment]
> @JeremyParish69 I'm a bit confused...should I retarget this PR for Frontier? Since you already created the other PR, I'm not sure whether this is needed any more?
> 
> Also, if a token is in the main app like ours, am I not supposed to send PRs targeting master any more?

Generally, most changes to master should be replicated to Frontier (but not necessarily the other way). In the future, it's still OK for you to propose changes to master, but because I happened to include these changes in my PR, this becomes redundant, however we are still in need to update in Frontier. Retargeting this to Frontier may work, but it also might try to bring over unwanted changes. If you are still confused, I can do it--I don't mind

**Comment by ankurdotb** [comment]
Gotcha! I rebased this from `frontier` base and resolved all merge conflicts. Hope this is good to go.

**Comment by ankurdotb** [comment]
@JeremyParish69 Rebased to remove conflicts again. BTW, the current `src/stores/root.ts` in the `frontier` branch is missing the trade router for pools 674, 703 among the ones that I could count. I'm not sure whether that's intentional, but I thought I'd let you know.

**Comment by JeremyParish69** [comment]
@ankurdotb , I'm liking all the changes I see under 'Files changed', so I'll make a new PR #487 with only the CHEQ gauge updates.

Thanks for letting me know that 647 was missing from the router on Frontier, which I've added. 703 is omitted since 704 is the 'canonical' pool for that pair.

**Comment by ankurdotb** [comment]
@JeremyParish69 Thanks, appreciate it! And would that then get rolled up to main as well automatically/you do batch merge commits upwards from frontier for the gauges? 

I can close this PR as a duplicate once it gets reflected on the UI.

**Comment by JeremyParish69** [comment]
> @JeremyParish69 Thanks, appreciate it! And would that then get rolled up to main as well automatically/you do batch merge commits upwards from frontier for the gauges?
> 
> I can close this PR as a duplicate once it gets reflected on the UI.

Yes, it can be closed. The changes have also been merged to Main in #478 since I happened to be working on a PR for Main, so I bundled it in.

**Pull request closed without merging**
