### PR TITLE
Cosmos Kit Upgrade type fix

### PR DESCRIPTION
**Pull request by NoahSaso**
## What is the purpose of the change

This fixes some bugs introduced by breaking changes in the latest Cosmos Kit upgrade.

## Brief Changelog

- Type error fix
- Change wallet image tag to `img` from Next's `Image` to support externally linked wallet images
- Fix Cosmos Kit breaking change fee setting

## Testing and Verifying

This change has been tested locally by rebuilding the website.

### CODE REVIEW

**Comment by JoseRFelix** [comment]
Thank you for the initiative! I really appreciate the help 🙏 

 After some QA, I could identify these issues: 

1. This error occurs while doing any transaction. I think it's related to some breaking change within the [account store](https://github.com/osmosis-labs/osmosis-frontend/blob/7e5589d91af0e3a9cdfb3a76d273fa8439e58aa2/packages/stores/src/account/base.ts#L417)
image

2. When trying to open the profile. The app crashes. I believe it's because of the wallet images. Next does not recognize the Custom DAO wallet. I suspect we'll have to change the Next Image component for `img` in [profile](https://github.com/osmosis-labs/osmosis-frontend/blob/7e5589d91af0e3a9cdfb3a76d273fa8439e58aa2/packages/web/modals/profile.tsx#L280) and [wallet select](https://github.com/osmosis-labs/osmosis-frontend/blob/7e5589d91af0e3a9cdfb3a76d273fa8439e58aa2/packages/web/modals/wallet-select.tsx#L433).

**Comment by NoahSaso** [comment]
> Thank you for the initiative! I really appreciate the help 🙏
> 
> After some QA, I could identify these issues:
> 
> 1. This error occurs while doing any transaction. I think it's related to some breaking change from Cosmos-Kit within the [account store signAndBroadcast](https://github.com/osmosis-labs/osmosis-frontend/blob/7e5589d91af0e3a9cdfb3a76d273fa8439e58aa2/packages/stores/src/account/base.ts#L417)
>    image
> 2. When trying to open the profile. The app crashes. I believe it's because of the wallet images. Next does not recognize the Custom DAO wallet. I suspect we'll have to change the Next Image component for `img` in [profile](https://github.com/osmosis-labs/osmosis-frontend/blob/7e5589d91af0e3a9cdfb3a76d273fa8439e58aa2/packages/web/modals/profile.tsx#L280) and [wallet select](https://github.com/osmosis-labs/osmosis-frontend/blob/7e5589d91af0e3a9cdfb3a76d273fa8439e58aa2/packages/web/modals/wallet-select.tsx#L433).

Perfect. I'll get right on those.

**Comment by NoahSaso** [comment]
@JoseRFelix, both issues have been fixed 👍

**Review by JoseRFelix — APPROVED** [review]
@NoahSaso LGTM 🚀 , thank you very much!

**Pull request merged**
