### PR TITLE
Lower routable pools 1k

### PR DESCRIPTION
**Pull request by jonator**
### ClickUp Task

[ClickUp Task URL](PASTE_CLICKUP_TASK_URL_HERE)

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Does this apply regardless of pool type, and regardless of whether the Unverified assets setting is toggled?

**Comment by jonator** [comment]
> Does this apply regardless of pool type, and regardless of whether the Unverified assets setting is toggled?

Yes

**Review by JeremyParish69 — CHANGES_REQUESTED** [review]
The preview does not seem to load pools below 10k (e.g., DYS, RAC, SUI, CRE--all missing) , and I can't select MEDAS, which has a couple pools above 10k.

**Review by MaxMillington — APPROVED** [review]

**Review by sunnya97 — APPROVED** [review]
Confirmed that the assets that @JeremyParish69 mentioned are now visible.

**Review by JeremyParish69 — APPROVED** [review]
LGTM. After turning OFF the Unverified setting, refreshing, and searching the swap widget, I can find assets that can only route through pools barely over $1000 (e.g., DYS). I couple of the assets I mentioned earlier no longer have >1000 liq in any pool, so not all are searchable, but that's to be expected.

**Pull request merged**
