### PR TITLE
added bze external gauges in web feature-flag

### PR DESCRIPTION
**Pull request by faneaatiku**

### CODE REVIEW

**Comment by faneaatiku** [comment]
Sorry for writing here but I wonder if this can be merged ? I half of hour are incentives start. We didn't know that a PR is required to show the incentives in FE, otherwise we would've submit this PR a lot earlier.

**Comment by JeremyParish69** [comment]
@faneaatiku  These gauges were set to run over only 2 and 4 epochs, so they are nearly done already. Will longer gauges be created (ideally at least 30 days)?

**Comment by faneaatiku** [comment]
> @faneaatiku These gauges were set to run over only 2 and 4 epochs, so they are nearly done already. Will longer gauges be created (ideally at least 30 days)?

Seems that I didn't understood the documentation. I started a new gauge. and modified the PR

**Review by JeremyParish69 — APPROVED** [review]
LGTM

**Pull request merged**
