### PR TITLE
Update chain-infos.ts for Shentu Chain (CTK)

### PR DESCRIPTION
**Pull request by yoongbok-lee**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
I notice the rest node has been updated. Can we have this validated using the preview link?

**Comment by JeremyParish69** [comment]
Better yet if we could have an initial liquidity pool created. I can't buy tokens to validate without any pool...

**Comment by yoongbok-lee** [comment]
We're currently looking into creating a pool on osmosis. I could send you some test tokens if you need some as well before that happens 👀

**Comment by JeremyParish69** [comment]
> We're currently looking into creating a pool on osmosis. I could send you some test tokens if you need some as well before that happens 👀

You could validate using the Deposit/Withdraw preview. Alternatively, I can validate but will need a small amt JeremyParish69.certik (certik1nqc9lk9tr472jxa9gxvxlamxnr67vcvpqvguym)

**Comment by yoongbok-lee** [comment]
Just sent you 1 CTK for testing. LMK if you need anything else!

**Comment by weffke** [comment]
I've tested it and was able to do a transfer CTK=>OSMO successfully

**Comment by weffke** [comment]
> I've tested it and was able to do a transfer CTK=>OSMO successfully

https://www.mintscan.io/shentu/txs/3DB488BA256866E21E5C87346ED5FEFE25DF06C7BE85C2C1C74FF1707CECF130

**Comment by yoongbok-lee** [comment]
updated RPC to fix the pending message. could you test it again?

**Comment by weffke** [comment]
> updated RPC to fix the pending message. could you test it again?

Looking good for me now!

**Review by JeremyParish69 — APPROVED** [review]

**Pull request merged**
