### PR TITLE
Add HOPE Junocw20

### PR DESCRIPTION
**Pull request by JeremyParish69**
Add HOPE Junocw20

### CODE REVIEW

**Comment by DADDY-XEP** [comment]
When PR Merge?

**Comment by jonator** [comment]
@DADDY-XEP  If possible, please use SVG over PNG.

**Comment by DADDY-XEP** [comment]
> 

has already been updated.  Thank you

**Comment by jonator** [comment]
Where has it been updated?

**Review by DADDY-XEP — CHANGES_REQUESTED** [review]
https://svgur.com/s/fHi

**Comment by HopeGalaxyNFT** [comment]
logo HOPE 250x250

**Comment by DADDY-XEP** [comment]
> logo HOPE 250x250

This is still a PNG format?

**Comment by jonator** [comment]
Could you please make a commit and replace [this](https://app.stargaze.zone/media/stars14sa4u42n2a8kmlvj3qcergjhy6g9ps06rzeth94f2y6grlat6u6sv9y4pd/7355) file with an SVG version? Thank you!

**Comment by JeremyParish69** [comment]
> Could you please make a commit and replace [this](https://app.stargaze.zone/media/stars14sa4u42n2a8kmlvj3qcergjhy6g9ps06rzeth94f2y6grlat6u6sv9y4pd/7355) file with an SVG version? Thank you!

it uses svg now

**Comment by DADDY-XEP** [comment]
Please start the merging. Thank you

**Comment by jonator** [comment]
@DADDY-XEP is there a pool for this?

**Comment by DADDY-XEP** [comment]
> 

Hi yes, pool 653 is live

https://app.osmosis.zone/pools?page=9

**Pull request merged**
