### PR TITLE
added tailwind wallet

### PR DESCRIPTION
**Pull request by baoskee**
## What is the purpose of the change

This pull request adds TAILWIND wallet to Osmosis supported wallets.

## Brief Changelog

- Adds `@cosmos-kit/tailwind-extension`

## Testing and Verifying

This change has been tested locally by rebuilding the website and verified content and links are expected

## Documentation and Release Note

This change adds TAILWIND wallet. See [tailwind.zone](https://tailwind.zone) for more info.
Extension link: https://chromewebstore.google.com/detail/tailwind-wallet/dpnfollacokcbkeiidhplhjpafkbfacj

## Summary by CodeRabbit

- **New Features**
	- Enhanced the wallet list in the app by adding "tailwind-extension" with its logo and specific properties, improving user options for wallet connectivity.

### CODE REVIEW

**Comment by jonator** [comment]
Please update from stage and the build should be fixed

**Comment by baoskee** [comment]
updated! @jonator can we run the Vercel preview again? : )

**Comment by jonator** [comment]
We're seeing errors in console that the tailwind_injected script is trying to set the readonly keplr object in window. Could you guys provide some background as to why that is?

**Comment by CryptoAssassin1** [comment]
@baoskee can you please share the invite codes one for me and other for @kamal-sutra

**Comment by baoskee** [comment]
> @baoskee can you please share the invite codes one for me and other for @kamal-sutra

Yes! 
- Extension link: https://chromewebstore.google.com/detail/tailwind-wallet/dpnfollacokcbkeiidhplhjpafkbfacj
- Invite code: LONG-OSMO

**Comment by baoskee** [comment]
> We're seeing errors in console that the tailwind_injected script is trying to set the readonly keplr object in window. Could you guys provide some background as to why that is?

Hi @jonator, we override the keplr API for those wanting to pay gas in USDC and the app has not yet supported Tailwind. Existing wallets like Phantom do this for Ethereum and Bitcoin dapps when they moved off Solana, and Rabby does this with MetaMask object so that their users can use Rabby everywhere. 

Both wallets just want to provide users the best experience if they choose them and we are doing that here as well. That said, we can patch this in next wallet version for Osmosis.zone URL if you want to eliminate this behavior on your app. It would be a simple content script change in the extension code that removes this behavior for app.osmosis.zone. Please let me know!

**Comment by sunnya97** [comment]
Hi @baoskee, yes we would very much appreciate turning off this functionality on Osmosis.

The current status quo of metamask hijacking in EVM world is something we want to avoid in Cosmos!

**Comment by baoskee** [comment]
> Hi @baoskee, yes we would very much appreciate turning off this functionality on Osmosis.
> 
> The current status quo of metamask hijacking in EVM world is something we want to avoid in Cosmos!

sounds good, can get wallet patch in by Monday-Tuesday next week (it takes a few days for Chrome store to approve; and it will be an independent release from this PR). Thanks!

**Comment by kamal-sutra** [comment]
@baoskee 1. when the page is refreshed, the wallet disconnects and when connect is clicked, it shows install wallet. But connects well after clicking the tailwind wallet. 
2. When depositing AKT or any other asset, it doesn't automatically select the same asset as network fee. 
3. For some reason AKT is not in the list of fee tokens although there is available balance.
4. Is it necessary to show whole list of other fee tokens for deposit tx? (unless you manually add every token as acceptable fee currencies) 
[Screencast from 23-03-24 12:55:09 PM IST.webm](https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/e10df303-e35b-44cf-ba99-2f247590899c)

**Comment by CryptoAssassin1** [comment]
@baoskee wallet is installed and i login successfully but im still getting Tailwind is not Isntalled.

https://github.com/osmosis-labs/osmosis-frontend/assets/103904125/e0dbcc60-17f7-41c8-95f8-0662dd2f7456

**Comment by baoskee** [comment]
> > Hi @baoskee, yes we would very much appreciate turning off this functionality on Osmosis.
> > The current status quo of metamask hijacking in EVM world is something we want to avoid in Cosmos!
> 
> sounds good, can get wallet patch in by Monday-Tuesday next week 🫡 (it takes a few days for Chrome store to approve; and it will be an independent release from this PR). Thanks!

Issue fixed in `1.18.2`! Should prevent content script override of `keplr` object on app.osmosis.zone and osmosis.zone.

**Comment by baoskee** [comment]
> @baoskee 1. when the page is refreshed, the wallet disconnects and when connect is clicked, it shows install wallet. But connects well after clicking the tailwind wallet. 2. When depositing AKT or any other asset, it doesn't automatically select the same asset as network fee. 3. For some reason AKT is not in the list of fee tokens although there is available balance. 4. Is it necessary to show whole list of other fee tokens for deposit tx? (unless you manually add every token as acceptable fee currencies) [Screencast from 23-03-24 12:55:09 PM IST.webm](https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/e10df303-e35b-44cf-ba99-2f247590899c)

1. Will triage and fix, thank you for pointing this out 🫡
2. This is a feature not a bug. The confusion for users is that they don't want to pick a different gas token for each chain. They should be able to pay with any gas token, and the wallet shows the preferred (default) gas token
3. Right now, we query only Osmosis balances for fee tokens, because we heavily depend on Osmosis Fee Abstraction. Next step we will query native balances and users will be able to use AKT not on Osmosis
4. Interesting idea! Right now we just take the intersection of all Osmosis allowable fee tokens in the Fee Abstraction module + those available on Osmosis. Is there a reason why users should have to whitelist each fee token before using it as gas?

**Comment by baoskee** [comment]
> @baoskee wallet is installed and i login successfully but im still getting Tailwind is not Installed.
> 
>  Trade.on.Osmosis.Zone.22.mp4

Thanks @CryptoAssassin1! This looks like @kamal-sutra's first issue; I will take a look and fix. Good catch.

**Comment by kamal-sutra** [comment]
> > @baoskee 1. when the page is refreshed, the wallet disconnects and when connect is clicked, it shows install wallet. But connects well after clicking the tailwind wallet. 2. When depositing AKT or any other asset, it doesn't automatically select the same asset as network fee. 3. For some reason AKT is not in the list of fee tokens although there is available balance. 4. Is it necessary to show whole list of other fee tokens for deposit tx? (unless you manually add every token as acceptable fee currencies) [Screencast from 23-03-24 12:55:09 PM IST.webm](https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/e10df303-e35b-44cf-ba99-2f247590899c)
> 
> 1. Will triage and fix, thank you for pointing this out 🫡
> 2. This is a feature not a bug. The confusion for users is that they don't want to pick a different gas token for each chain. They should be able to pay with any gas token, and the wallet shows the preferred (default) gas token
> 3. Right now, we query only Osmosis balances for fee tokens, because we heavily depend on Osmosis Fee Abstraction. Next step we will query native balances and users will be able to use AKT not on Osmosis
> 4. Interesting idea! Right now we just take the intersection of all Osmosis allowable fee tokens in the Fee Abstraction module + those available on Osmosis. Is there a reason why users should have to whitelist each fee token before using it as gas? 
> 

Thanks for all the clarifications. 
Point 4 is moot if 2 is a feature.

**Comment by baoskee** [comment]
Looks like I tested _without_ Keplr extension installed, so all these issues I was able to reproduce with Keplr extension also installed. Will test under this condition next time 🫡

- `1.18.3` TAILWIND Extension patch fixes "Installed Wallet" issue when wallet is already installed 
- should take 1-2 days for approval 

For refreshing after connect issue: 
- https://github.com/cosmology-tech/cosmos-kit/pull/419 fixes race conditions on refresh when wallet is already connected. This is a non-deterministic error after TAILWIND is already connected
- Your call to wait, or merge without the CosmosKit upgrade

Also for the `keplr` override issue, these are the hostnames I added to skip-list:
```typescript
const KEPLR_HOSTNAME_SKIPLIST = ["osmosis.zone", "app.osmosis.zone"];
```
So the extension still overrides on local and preview environments, but it won't override in production. Let me know what other domains you want to add to this list.

**Comment by baoskee** [comment]
> Looks like I tested _without_ Keplr extension installed, so all these issues I was able to reproduce with Keplr extension also installed. Will test under this condition next time 🫡
> 
> * `1.18.3` TAILWIND Extension patch fixes "Installed Wallet" issue when wallet is already installed
> * should take 1-2 days for approval
> 
> For refreshing after connect issue:
> 
> * [Fix/tailwind race condition cosmology-tech/cosmos-kit#419](https://github.com/cosmology-tech/cosmos-kit/pull/419) fixes race conditions on refresh when wallet is already connected. This is a non-deterministic error after TAILWIND is already connected
> * Your call to wait, or merge without the CosmosKit upgrade
> 
> Also for the `keplr` override issue, these are the hostnames I added to skip-list:
> 
> ```ts
> const KEPLR_HOSTNAME_SKIPLIST = ["osmosis.zone", "app.osmosis.zone"];
> ```
> 
> So the extension still overrides on local and preview environments, but it won't override in production. Let me know what other domains you want to add to this list.

All issues addressed! Rebased stage branch and updated new lockfile with `@cosmos-kit/tailwind-extension` version 1.0.3. 🫡

**Comment by baoskee** [comment]
Hi guys @kamal-sutra @CryptoAssassin1 @jonator. Can I get an update for this?

**Comment by kamal-sutra** [comment]
@baoskee can you update the branch to latest stage or prod.

**Comment by kamal-sutra** [comment]
With Keplr extension enabled or disabled, when osmosis page is refreshed it disconnects Tailwind and asks to connect/install

image
image

**Comment by kamal-sutra** [comment]
While depositing Atom or any asset, it shows Osmo as network fee on Tailwind tx window, but it is taking Atom only as fee (can be seen on mintscan). So, is it a network fee display bug or the multi token fee feature is not working?
image
image

**Comment by kamal-sutra** [comment]
Keplr extension is disabled. Click connect wallet and select Keplr, it is still connecting keplr (which should not)
[Screencast from 23-04-24 01:08:32 PM IST.webm](https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/af4128e9-7989-48b1-ade6-f6e0ca8076e0)

**Comment by CryptoAssassin1** [comment]
@kamal-sutra you are testing on old perview deploy.
@jonator can you please approve new deploy.

**Comment by sunnya97** [comment]
I approved

**Comment by CryptoAssassin1** [comment]
@sunnya97 build failed.

**Comment by MaxMillington** [comment]
@baoskee any update on this? Otherwise I'm going to close the stale PR

**Comment by JoseRFelix** [comment]
Closing this PR as it's stale

**Pull request closed without merging**
