### PR TITLE
add help button

### PR DESCRIPTION
**Pull request by MaxMillington**
## What is the purpose of the change:

Adds a help button to the top nav with relevant links

Note that the existing styles in the app are not aligned to Figma currently. As a separate task, we should unify the design language, but the styles in this PR are identical to the existing conventions in the app so as to keep the app consistent
Screenshot 2024-07-09 at 3 51 57 PM
Screenshot 2024-07-09 at 3 51 53 PM

### Linear Task

[Linear Task URL](https://linear.app/osmosis/issue/FE-509/add-help-section-to-top-nav)

## Brief Changelog

Adds new button for top nav for the help section

## Testing and Verifying

This change has been tested locally by rebuilding the website and verified content and links are expected

### CODE REVIEW

**Comment by sunnya97** [comment]
CleanShot 2024-07-10 at 16 00 57@2x

For me, its opening to the right, and thinner than your screenshot for some reason.

Also, can we make the colors of the icons all match what's used for the settings button next to it

**Comment by MaxMillington** [comment]
> CleanShot 2024-07-10 at 16 00 57@2x
> 
> For me, its opening to the right, and thinner than your screenshot for some reason.
> 
> Also, can we make the colors of the icons all match what's used for the settings button next to it

@kamal-sutra @CryptoAssassin1 are you guys able to reproduce this? I cannot.

**Comment by CryptoAssassin1** [comment]
@MaxMillington yes.
Screenshot from 2024-07-11 01-47-55

**Comment by kamal-sutra** [comment]
@MaxMillington Please check Build failed

**Review by jonator — CHANGES_REQUESTED** [review]
Seems the padding on the button causes uneven gap between the flex items:
Screenshot 2024-07-16 at 9 40 51 PM

On tablets, seems there's an overflow issue with the nav bar buttons. This may be a design issue. Particularly on the portfolio page:
Screenshot 2024-07-16 at 9 43 27 PM



Seems absolute positioning is to the right:
Screenshot 2024-07-16 at 9 41 45 PM

Are these meant to be accessible on mobile? Likely also a design Q:
Screenshot 2024-07-16 at 9 44 59 PM

**Pull request closed without merging**
