### PR TITLE
Add HongKongese(zh-hk) translation

### PR DESCRIPTION
**Pull request by PikachuEXE**

### CODE REVIEW

**Comment by jonator** [comment]
thanks! We're about to release v13 frontend which includes new translations. Once that comes in you can merge and add the new ones.

**Comment by PikachuEXE** [comment]
Let me know when I should update the translations
I am maintaining `zh-tw` one too

**Comment by PikachuEXE** [comment]
Rebased, missing translation entries added & translated

**Comment by jonator** [comment]
We can test in preview

**Review by jonator — APPROVED** [review]

**Pull request merged**
