### PR TITLE
feat: :bento: add homepage bitcoin prop

### PR DESCRIPTION
**Pull request by DavideSegullo**
## What is the purpose of the change:

Add new homepage image below wosmongton.

### Linear Task

[Linear Task URL](https://linear.app/osmosis/issue/FE-545/update-wosmongton)

### CODE REVIEW

**Review by MaxMillington — APPROVED** [review]

**Review by yury-dubinin — APPROVED** [review]
lgtm

**Comment by MaxMillington** [comment]
Screenshot 2024-06-17 at 2 07 34 PM
@DavideSegullo feels like the alignment is a little off?

**Review by MaxMillington — CHANGES_REQUESTED** [review]
Is the alignment right? Looks weird on my machine

**Comment by DavideSegullo** [comment]
> Is the alignment right? Looks weird on my machine

prod behaves in the same way

Screenshot 2024-06-17 alle 20 08 48

**Review by MaxMillington — APPROVED** [review]
Maybe that's just how we want it. Let's just get an approval from aaron and david

**Comment by yury-dubinin** [comment]
Prod vs Preview
Screenshot 2024-06-17 at 20 14 14

**Review by CryptoAssassin1 — APPROVED** [review]

**Review by kamal-sutra — APPROVED** [review]

**Pull request merged**
