### PR TITLE
Cosmetic improvements v2

### PR DESCRIPTION
**Pull request by jonator**
## Notable changes

Closes: #588 

* Click top left logo to go to trade page
* Frontier
  * Update toast color
  * Mobile - improve banner spacing
  * Show banner once per browser

### Trade page

* Token select:
  * Sort tokens by fiat value descending
  * Display chain name, and channel if channel not canonical
  * Search by chain name, min denom ("basecro"), peg mechanism ("collateralized," "hybrid," "algorithmic")
* Remove denom in from field, max 8 decimals

### Pool detail page
* Requery superfluid validator data after sending go superfluid msg
* 14 day gauge uses one osmosis icon for sfs tooltip
* Add liquidity tokens scroll for pools with 3+ tokens
* Bond modal stays open with button loading animation for bond msgs
* Pool catalyst shows decimal precision even for > 1 amounts

### Pools page
* Search pools by network names (appended: "Cosmos Hub Akash Network") and peg mechanism

### Assets page
* Sorting by balance sorts by fiat value, not amounts

### CODE REVIEW

**Comment by delivan** [comment]
@jonator What peg mechanism is for? Did users want to search pools by peg mechanism?

**Comment by jonator** [comment]
@delivan Peg mechanism is used to label the type of stable asset for the info box in the add liquidity modal, as well as for searchiing

**Comment by jonator** [comment]
@delivan made a few last minute changes. Feel free to review again

**Comment by delivan** [comment]
- [ ] I think the font size of the 'Available LP Token' section(label and value) looks small. Why don't you make it bigger so that users can see it more clearly?
스크린샷 2022-06-15 오전 12 01 56
- [ ] 'Hide zero balances' is unavailable for me
스크린샷 2022-06-14 오후 11 57 53
- [ ] The amount of token shrinks whenever switching token on token select

**Comment by jonator** [comment]
> The amount of token shrinks whenever switching token on token select

This is how the old app functioned and it makes sense given that fee is subtracted

**Comment by jonator** [comment]
> I think the font size of the 'Available LP Token' section(label and value) looks small. Why don't you make it bigger so that users can see it more clearly?

IMO the font size is fine, I'm letting @victortokaito determine if there needs to be a change here.

**Review by delivan — APPROVED** [review]

**Pull request merged**
