### PR TITLE
Add ampOSMO

### PR DESCRIPTION
**Pull request by JeremyParish69**
## What is the purpose of the change

To add the ampOSMO token

## Brief Changelog

-adds ampOSMO to Osmosis assets
-adds ampOSMO logo image

## Testing and Verifying

This change has been tested locally by rebuilding the website and verified content and links are expected

### CODE REVIEW

**Comment by sunnya97** [comment]
@JeremyParish69 is this g2g?

**Comment by JeremyParish69** [comment]
> @JeremyParish69 is this g2g?

We're waiting on a pool which is supposed to be very soon.

**Comment by sunnya97** [comment]
@JeremyParish69 can you start adding a checklist of what's done and what's needed to these asset listing PRs

**Comment by JeremyParish69** [comment]
> @JeremyParish69 can you start adding a checklist of what's done and what's needed to these asset listing PRs

I'll be including a link to the checklist that will be in the description of the corresponding PR to the Assetlists repo, and I'll try to keep better record of what's remaining here as well

**Pull request merged**
