### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by sehyunc**
`en.json`
* add localization for helper text

existing PR but changed base branch

### CODE REVIEW

**Comment by jonator** [comment]
Are you planning on adding for other languages?

**Comment by sehyunc** [comment]
> Are you planning on adding for other languages?

I can if you'd like. Are there languages that are prioritized or should I add a Google Translated version for all localizations that currently exist?

**Comment by jonator** [comment]
We should try to always update them as best we can with google translate, then consult others/natives later on the correctness.

**Comment by sehyunc** [comment]
> We should try to always update them as best we can with google translate, then consult others/natives later on the correctness.

Ok, will update PR with other localizations.

**Comment by jonator** [comment]
Think you could bundle this issue into your PR?
Issue #1160

**Comment by sehyunc** [comment]
> Think you could bundle this issue into your PR?
> 
> Issue #1160 

Yep, will make this change in the Polish localization too!

**Comment by PikachuEXE** [comment]
Will review `zh-tw` when it's ready

**Review by jonator — APPROVED** [review]

**Review by jonator — CHANGES_REQUESTED** [review]
Please resolve merge conflicts

**Comment by jonator** [comment]
@PikachuEXE LMK what you think of zh-tw

**Comment by PikachuEXE** [comment]
What should I do to make `stablecoinTypes.collateralized` appear...
I know it's rendered by https://github.com/osmosis-labs/osmosis-frontend/blob/stage/packages/web/components/complex/add-liquidity.tsx#L194 but reading the code doesn't make it easier to know how to test...

**Comment by sehyunc** [comment]
> What should I do to make `stablecoinTypes.collateralized` appear... I know it's rendered by https://github.com/osmosis-labs/osmosis-frontend/blob/stage/packages/web/components/complex/add-liquidity.tsx#L194 but reading the code doesn't make it easier to know how to test...

You can find it by going to Pools > USDC/OSMO Pool (or any pool with a stablecoin on one side) > Add Liquidity, and you should see it as helper text beneath the stablecoin. 
image

**Review by jonator — CHANGES_REQUESTED** [review]
First update from stage branch, as I think I fixed a few of these:

* fr.json `stablecoinWarning` is missing in `addLiquidity`
* ko.json remove `pool.shares`, `errors.insufficientBal` missing
* pl.json remove `pool.shares` & `pool.unbonded`, add `stablecoinWarning`
* ro.json add `stablecoinTypes.**`
* zh-cn.json add `stablecoinWarning`
* zh-tw.json remove `pool.shares`, add `selectToken.**`

Tip: in VSCode, right click the en.json in file tree, and select "Select for compare", then you can right click another translation file and click "Compare with Selected" and you can easily spot these differences.

**Comment by sehyunc** [comment]
@jonator Could we make a type and use it in 'use-current-language' hook when importing JSONS so if they're out of sync with each other it'll give a more explicit error?

**Comment by jonator** [comment]
IDK if that would fix our problem at runtime? That would require typescript to read the JSON at build time and type check it against our new type, which I don't think is possible.

Alternatively, we could write a node script to find missing members compared to en.json. It could additionally find all uses of `t()` in components and make sure there's no extraneous members in the json files (something diff-ing doesn't help with, and is otherwise a highly manual process).

**Comment by sehyunc** [comment]
> IDK if that would fix our problem at runtime? That would require typescript to read the JSON at build time and type check it against our new type, which I don't think is possible.
> 
> 
> 
> Alternatively, we could write a node script to find missing members compared to en.json. It could additionally find all uses of `t()` in components and make sure there's no extraneous members in the json files (something diff-ing doesn't help with, and is otherwise a highly manual process).
> 
> 
> 
> There is [this](https://dev.to/nickytonline/strongly-typed-json-in-typescript-5gb2), but I don't think it works in our case since we're using dynamic imports to reduce bundle size.

You're right, I see now we're dynamically importing it, which makes type safety a bit harder. Manual checking seems fine though.

**Review by PikachuEXE — APPROVED** [review]
`zh-tw` looks fine~
image

**Comment by PikachuEXE** [comment]
Can we have `zh-hk` updated (just copy from `zh-tw`) too?
Since #1051 is already merged

**Comment by sehyunc** [comment]
@jonator Since #1051 was merged into `main`, I don't have that commit since I branched off of `stage`. Should I just copy and paste `zh-hk` for now?

**Comment by sehyunc** [comment]
Added!

**Review by PikachuEXE — APPROVED** [review]

**Review by jonator — CHANGES_REQUESTED** [review]
@sehyunc Please address comments from former review. Additionally:

* zh-hk.json missing `pools.myLiquidity`, missing last 4 keys in `swap`, remove `pool.unbonded`, missing `menu.buyTokens`,

**Comment by sehyunc** [comment]
> @sehyunc Please address comments from former review. Additionally:
> 
> * zh-hk.json missing `pools.myLiquidity`, missing last 4 keys in `swap`, remove `pool.unbonded`, missing `menu.buyTokens`,

Sorry, misunderstood your previous comment, I thought you had made those changes on this branch. Updating this now.

**Review by jonator — CHANGES_REQUESTED** [review]
Found a few more:
* ko.json remove `pool.shares`
* pl.json add `addLiquidity.stablecoinWarning`

**Comment by jonator** [comment]
Hey @PikachuEXE really appreciate your initiative to jump in and check this stuff! Email me and we can get you an OSMO grant for your work.

**Review by jonator — APPROVED** [review]

**Pull request merged**
