### PR TITLE
added Romanian translations

### PR DESCRIPTION
**Pull request by faneaatiku**

### CODE REVIEW

**Comment by jonator** [comment]
https://github.com/osmosis-labs/osmosis-frontend/blob/ed5c30719a960a93aab327b0950cbd7014c2d973/packages/web/stores/user-settings/language.tsx#L41-L45

Please add the appropriate language key and display name to the settings dropdown.

**Comment by faneaatiku** [comment]
> https://github.com/osmosis-labs/osmosis-frontend/blob/ed5c30719a960a93aab327b0950cbd7014c2d973/packages/web/stores/user-settings/language.tsx#L41-L45
> 
> Please add the appropriate language key and display name to the settings dropdown.

Done! Sorry I missed it initially. Waiting for a preview so I can check it in the actual context of the interface. 
Thanks

**Comment by jonator** [comment]
OK preview incoming

**Comment by faneaatiku** [comment]
> OK preview incoming

Looks good! Made some small changes that weren't fitting the context. IMHO, as a native Romanian, it looks good.

**Comment by jonator** [comment]
This is very appreciated, thank you.

**Review by jonator — APPROVED** [review]

**Pull request merged**
