### PR TITLE
Publish Stage

### PR DESCRIPTION
**Pull request by jonator**
* fix nil values sorting with a given sort key
* Add useAmountInput integration tests
* Take into account manual entry for Swap's Max/Half
* Change swap fee tokens automatically if there's not enough balance to pay fees

### CODE REVIEW

**Review by JoseRFelix — APPROVED** [review]

**Review by sunnya97 — APPROVED** [review]
utAck

**Comment by jonator** [comment]
QA is offline for testing, and don't want to deploy on Friday, so I propose we deploy Monday.

**Comment by jonator** [comment]
Stepper is broken

**Comment by jonator** [comment]
NVM

**Comment by jonator** [comment]
Wait stepper IS broken

**Pull request merged**
