### PR TITLE
Feat/add station extension

### PR DESCRIPTION
**Pull request by alecande11**
## What is the purpose of the change

This PR add support for the Station extension and replaces all links to `terra.money` domains.

### ClickUp Task

N/A

## Brief Changelog

- Use Station cosmos-kit package for connection to the extension
- Replace alle terra.money links with their station.money equivalent

## Testing and Verifying

This change has been tested locally with Station extension v7.4.4 (make sure you are on the latest version during tests), both connection and tx signing works fine.

## Documentation and Release Note

- Does this pull request introduce a new feature or user-facing behavior changes? yes
- How is the feature or change documented? not aplicable, it's pretty straightforward for users to connect to station if they already have the extension installed. Documentations on how to setup the Station extension are available [here](https://setup.station.money/).

### CODE REVIEW

**Comment by JoseRFelix** [comment]
Thank you for your input, @alecande11! Do you know if the Station wallet now supports the feature of adding custom chains, known as "Suggest Chain"? It didn't in the past. I'm asking because they won't be compatible until #1981 is merged

**Comment by alecande11** [comment]
Hi @JoseRFelix !
No, unfortunately our extension doesn't support the suggestChain method.
We have a similar method under development but it's mainly meant for developers and we rely solely on LCDs instead of RPCs so the chain information required would be different than Keplr and other wallets.

**Review by jonator — APPROVED** [review]

**Comment by sunnya97** [comment]
@JoseRFelix what happened to this?

**Comment by JoseRFelix** [comment]
@sunnya97 I closed this one in favor of #2130. The integration is ready from our side, but the station sign window is flaky and sluggish. I communicated this to the Station team, but I haven't received answers

**Pull request closed without merging**
