### PR TITLE
Xmas Theme

### PR DESCRIPTION
**Pull request by daniel-farina**

### CODE REVIEW

**Comment by gnujoow** [comment]
happy Christmas everyone

**Review by jonator — CHANGES_REQUESTED** [review]
Screen Shot 2022-12-23 at 12 38 09 PM

I can still see the old background in the top and bottom of the screen

**Comment by daniel-farina** [comment]
> I can still see the old background in the top and bottom of the screen

I'm adding a very simple login to remove these classes from the div, quick dirty fix for now.

```
<div className={(IS_FRONTIER ? 'absolute h-full w-full bg-home-bg-pattern bg-cover bg-repeat-x' : '')}>
```

**Comment by jonator** [comment]
Eh I'm still not a fan of it not being fit to the page

**Review by daniel-farina — COMMENTED** [review]
lgtm

**Pull request merged**
