### PR TITLE
Add Gravity Bridge ETH, USDC, DAI, and USDT

### PR DESCRIPTION
**Pull request by ChristianBorst**
Added images for ETH, USDC, DAI, and USDT
Reordered the GammSwapManager entries by poolId because it made it hard to spot at a glance if a pool was included already
Added pools 633 (gUSDC/OSMO), 634 (gWETH/OSMO), and 670 (gUSDC/OSMO) to the GammSwapManager entries

### CODE REVIEW

**Comment by ChristianBorst** [comment]
Before this is merged, could someone affirm that I am unable to add https://app.osmosis.zone/pool/635 to the GammSwapManager entries **because it has 3 assets**? It would appear that currently 635 is the only DAI pool created at the moment and I would like to include it if possible.

Thanks.

**Comment by JeremyParish69** [comment]
> Before this is merged, could someone affirm that I am unable to add https://app.osmosis.zone/pool/635 to the GammSwapManager entries **because it has 3 assets**? It would appear that currently 635 is the only DAI pool created at the moment and I would like to include it if possible.
> 
> Thanks.

I think you're okay to add this listing all 3 assets. I will test it to be sure.

**Comment by ChristianBorst** [comment]
I made a couple changes:
* Removed some notes I accidentally left in src/config.ts when defining the WETH USDC DAI and USDT tokens, oops
* Added in pool 635

**Comment by JeremyParish69** [comment]
good news, @ChristianBorst --the triple asset pool works fine in the trade router.

A few more requested changes, please:

-Can you get new images for WETH that are square aspect ratio? The tall logo image gets squished vertically.
-Will there soon be USDT liquidity we can add here?
-If it's not too much trouble, could you put the order of pools in the router back to what it was? It not only affects the order of appearance in the dropdown (which we're trying to keep chronological to listing date), but also introduces conflicts when merging master back into frontier branch.

**Review by JeremyParish69 — APPROVED** [review]
LGTM

**Comment by ChristianBorst** [comment]
Thanks for all the help getting this ready and polished!

**Pull request merged**
