### PR TITLE
Draft: AutoBond [HackAtom VI]

### PR DESCRIPTION
**Pull request by tennox**
https://devpost.com/software/osmosis-semi-auto-compound

Screenshot single-in

### CODE REVIEW

**Comment by tennox** [comment]
This PR currently includes some commits for a different contribution we're planning to do:
A one-click gitpod development environment for osmosis, including running a local net.

We will separate those into a separate PR soon. sorry for the confusion.

**Comment by gotjoshua** [comment]
> Closing due to refactor

What does that mean actually? It doesn't fit any more because osmosis had been refactored since the pr?

**Comment by jonator** [comment]
In short, yes. This code would become obsolete.

However, I think this is a good idea and we'd love to collaborate on you adding this once we get the refactor completed. We've had discussions this week about streamlining the IBC Deposit -> Bond workflow (currently has quite a few steps involved). If you'd like, we could loop you in on design and we could have you add it? Thanks again for the contribution!

**Comment by tennox** [comment]
We're definitely curious, let us know when the time has come :)
Greetings and good refactoring!
~Manu ;)

**Pull request closed without merging**
