### PR TITLE
feat: Show Osmosis Updates

### PR DESCRIPTION
**Pull request by JoseRFelix**
## What is the purpose of the change

Show Osmosis updates whenever they are available. Content is managed in the [fe-content](https://github.com/osmosis-labs/fe-content/blob/main/cms/osmosis-update.json) repo. If the user closes the updates notice, he should not see it until a new URL is available.

## Brief Changelog

image

## Testing and Verifying

- [ ] Display notice when an update is available
- [ ] Closing the notice should not show it again even after reload

### CODE REVIEW

**Comment by CryptoAssassin1** [comment]
@JoseRFelix can we add demo to see how its going to look?
Screenshot from 2023-11-17 14-08-21

**Comment by kamal-sutra** [comment]
Doesn't show "Osmosis updates" for me. cleared cache. probably a demo update should be made to test it.

image

**Review by jonator — APPROVED** [review]
LGTM

**Comment by JoseRFelix** [comment]
> Doesn't show "Osmosis updates" for me. cleared cache. probably a demo update should be made to test it.

That's weird. Can you share a screenshot of your network tab to see the response result?

**Comment by JoseRFelix** [comment]
> @JoseRFelix can we add demo to see how its going to look?

Please try again now. I added a public link

**Comment by kamal-sutra** [comment]
Works as intended
image
image

After closing the updates notice
image

**Review by kamal-sutra — APPROVED** [review]

**Comment by CryptoAssassin1** [comment]
@JoseRFelix translation is missing.
Screenshot from 2023-11-17 21-35-52

**Comment by JoseRFelix** [comment]
@CryptoAssassin1 Translations have been added 👍 , thank you!

**Review by CryptoAssassin1 — APPROVED** [review]
looking good.

**Pull request merged**
