### PR TITLE
feat: Add Global Settings Modal

### PR DESCRIPTION
**Pull request by JoseRFelix**

### CODE REVIEW

**Comment by sunnya97** [comment]
Task linked: [CU-3y25v5e Asset lists + Settings Modal - Design](https://app.clickup.com/t/3y25v5e)

**Comment by JoseRFelix** [comment]
@jonator Thanks for the review! Addressed the feedback 👍

**Review by jonator — COMMENTED** [review]
We should be able to remove the whole control/icon-dropdown modal, and any associated single-use types.

**Comment by JoseRFelix** [comment]
> We should be able to remove the whole control/icon-dropdown modal, and any associated single-use types.

You're right! Deleted all these extra dead code on my latest commit

**Comment by jonator** [comment]
@JoseRFelix Please address merge conflicts, then I'll merge #1201

**Comment by JoseRFelix** [comment]
> @JoseRFelix Please address merge conflicts, then I'll merge this then #1201

@jonator Done

**Review by jonator — APPROVED** [review]

**Comment by jonator** [comment]
Great work!

**Pull request merged**
