### PR TITLE
feat: CMS Staking URL

### PR DESCRIPTION
**Pull request by DavideSegullo**
## What is the purpose of the change

Implement CMS staking URL.

### ClickUp Task

[ClickUp Task URL](PASTE_CLICKUP_TASK_URL_HERE)

### CODE REVIEW

**Review by MaxMillington — APPROVED** [review]

**Comment by arispech** [comment]
what do you mean available for somm and osmosis? What page should we be checking? Currently the stake page only shows Osmosis and the link on SOMM takes you to keplr dashboard.

**Comment by DavideSegullo** [comment]
> what do you mean available for somm and osmosis? What page should we be checking? Currently the stake page only shows Osmosis and the link on SOMM takes you to keplr dashboard.

Within the asset detail pages, there is a section to indicate the staking page of the displayed asset.
It is now a CMS-configurable parameter, and we currently only show it for Osmo and Somm

Screenshot 2023-12-13 alle 00 41 01

**Review by kamal-sutra — APPROVED** [review]
Displays the staking url and pools url for both somm and osmo.

image

image

**Comment by DavideSegullo** [comment]
> ok working well on my end
> 
> * Somm page shows the link to stake and redirects to Keplr
> * Osmosis shows the link to stake and redirects to the redirect to Keplr staking page. Is the osmosis link supposed to take you to the stake page on our front end instead?

2) Yes, we'll switch it later, right now it's an external link

**Comment by CryptoAssassin1** [comment]
Earn tab is not visible on other languages
image

**Pull request merged**
