### PR TITLE
feat: Update Amplitude Events

### PR DESCRIPTION
**Pull request by JoseRFelix**
## To Do

- [ ] Add `Settings: pools < $0.01 toggle` to Amplitude @victortokaito 
- [ ] Remove `unbondingPeriod` from `Pool detail: Earn more by bonding clicked`
- [ ] Make sure there are no invalid events: #1291

### CODE REVIEW

**Comment by jonator** [comment]
@JoseRFelix by todo, does that mean you have outstanding work? If so please make this a draft PR

**Comment by jonator** [comment]
Hey @JoseRFelix could we try to address this https://github.com/osmosis-labs/osmosis-frontend/issues/1291 in this PR since we're touching Amplitude events already?

**Review by jonator — CHANGES_REQUESTED** [review]
Let's address this in this work:
https://github.com/osmosis-labs/osmosis-frontend/issues/1291

**Comment by JoseRFelix** [comment]
> Let's address this in this work:
https://github.com/osmosis-labs/osmosis-frontend/issues/1291

Sounds good. This PR addresses most of the invalid events, but I'll do a double-check

**Comment by jonator** [comment]
Stale, can be reopened later if needed.

**Pull request closed without merging**
