### PR TITLE
Frontier - Add Rizon

### PR DESCRIPTION
**Pull request by jayjay-crypto**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
@jayjay-crypto fantastic job with these PRs. The only issue is that we can't add atolo to the Trade Router with such low liquidity. Are we able to get this up to at least $1000? alternatively we can add it without adding to the Trade page...

**Comment by Rizonian** [comment]
Hi Jeremy, we will check the swap fee. 
Does $1000 means pool size?

**Comment by JeremyParish69** [comment]
> Hi Jeremy, we will check the swap fee. Does $1000 means pool size?

Thanks for checking, as 2% is unusual and much higher than all other pools in the trade router.
Yes, the $1000 is referring to total pool size.

**Comment by JeremyParish69** [comment]
pausing Frontier additions. Will create a new PR to add as a Frontier token to refactored branch.

**Comment by JeremyParish69** [comment]
Can we please use secure (https) for the endpoints? The current ones do not respond to https...

**Comment by jayjay-crypto** [comment]
Hi @JeremyParish69 sorry for the late feed back. Rizon's team have open a new pool with good fees, 0.2%, and more liquidity, it's pool 729. Can we re-add Rizon to the router and finish the PR

**Pull request merged**
