### PR TITLE
fix: don't show chart unavailable when loading

### PR DESCRIPTION
**Pull request by jonator**
## What is the purpose of the change

When the user changed the chart time range, the chart would flicker "unavailable" while loading. Now, we check if it's loading and only show if we know there's no data.

### ClickUp Task

[ClickUp Task URL](PASTE_CLICKUP_TASK_URL_HERE)

### CODE REVIEW

**Review by JoseRFelix — APPROVED** [review]

**Comment by sunnya97** [comment]
Can we have it show a loading animation?

**Comment by jonator** [comment]
> Can we have it show a loading animation?

Are you thinking a spinner? That would be easiest right now

**Comment by sunnya97** [comment]
Yeah

**Comment by jonator** [comment]
@sunnya97 added loader

**Pull request merged**
