### PR TITLE
Use SSR computation for poolId parameter

### PR DESCRIPTION
**Pull request by fabryscript**
## What is the purpose of the change

This makes the computation of the `poolId` parameter present in the `[id].tsx` page server side in order to fix the issue of the id not displaying correctly in link previews

## Testing and Verifying

This change has been tested locally by rebuilding the website and verified content and links are expected

### CODE REVIEW

**Comment by fabryscript** [comment]
As we saw previously in the PR #2666, the result of using `getStaticProps` & `getStaticPaths` is an OOM error which is probably caused by the eccessive size of the pages that needs to be iterated through in order to obtain all of the possible ids in `getStaticPaths`. For this reason, I do think that it is better to fix the issue by using SSR and accepting the tradeoff of the possibility that the initial loading time could be a little slower than usual

**Comment by jonator** [comment]
From the preview, I haven't found the SSR to cause much of a noticeable perf problem.

**Review by jonator — APPROVED** [review]

**Review by DavideSegullo — APPROVED** [review]

**Comment by fabryscript** [comment]
> @fabryscript what's the status of this one?

It seems to work fine

**Comment by fabryscript** [comment]
@MaxMillington Are there any updates concerning to the bounty redeem? I have not yet recieved a response from the first mail they sent me

**Comment by MaxMillington** [comment]
@fabryscript it takes around a month for them to process. If you have not received it after a month, let me know and I will take care of it

**Comment by fabryscript** [comment]
> @fabryscript it takes around a month for them to process. If you have not received it after a month, let me know and I will take care of it

Perfect, thanks for the response

**Pull request merged**
