### PR TITLE
Add Pool 638 to Trade router

### PR DESCRIPTION
**Pull request by Konstellation**
Add Pool 638 to Trade router

### CODE REVIEW

**Review by JeremyParish69 — CHANGES_REQUESTED** [review]
There is already the pool:udarc alternativeCoinId defined using the Osmo/Darc pool, and should not be defined multiple times. Please delete the additional alternativeCoinId definition you've added.

Also, what is channel 304? Konstellation is through channel 171. Please correct this

**Comment by Konstellation** [comment]
> There is already the pool:udarc alternativeCoinId defined using the Osmo/Darc pool, and should not be defined multiple times. Please delete the additional alternativeCoinId definition you've added.
> 
> Also, what is channel 304? Konstellation is through channel 171. Please correct this

Hi, thank you for your comment. we added another IBC channel with udarc and uatom. How do we add here?

**Comment by ejj3289** [comment]
> There is already the pool:udarc alternativeCoinId defined using the Osmo/Darc pool, and should not be defined multiple times. Please delete the additional alternativeCoinId definition you've added.
> 
> Also, what is channel 304? Konstellation is through channel 171. Please correct this

Hi @JeremyParish69 , thanks for reply and we made change there. Please take a look once more thanks in advance.

**Comment by Konstellation** [comment]
> There is already the pool:udarc alternativeCoinId defined using the Osmo/Darc pool, and should not be defined multiple times. Please delete the additional alternativeCoinId definition you've added.
> 
> Also, what is channel 304? Konstellation is through channel 171. Please correct this

Updated. Please check.

**Review by JeremyParish69 — APPROVED** [review]
Looks good!

**Pull request merged**
