### PR TITLE
add PLTN

### PR DESCRIPTION
**Pull request by PLTNDeploy**

### CODE REVIEW

**Comment by PLTNDeploy** [comment]
What is missing to move forward 
@JeremyParish69

**Comment by jonator** [comment]
Pending addition of LISTING.md

**Comment by JeremyParish69** [comment]
Apologies for the delay, @PLTNDeploy, we've been working to finalize [listing requirements](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md).
Note that tokens can no longer be listed by new GitHub accounts. Is there a more credible GitHub user with a verifiable history that can vouch for this token?

**Comment by jonator** [comment]
Closing for now, can reopen

**Pull request closed without merging**
