### PR TITLE
change wallet order

### PR DESCRIPTION
**Pull request by MaxMillington**
## What is the purpose of the change:

Change wallet order

### CODE REVIEW

**Comment by sunnya97** [comment]
I don't think this changed anything in the actual order on the site
CleanShot 2024-06-14 at 11 37 41@2x

**Comment by MaxMillington** [comment]
> I don't think this changed anything in the actual order on the site CleanShot 2024-06-14 at 11 37 41@2x

yea, I meant to put this in draft. it's just an experiment

**Review by DavideSegullo — APPROVED** [review]

**Comment by yury-dubinin** [comment]
wallets

**Review by yury-dubinin — APPROVED** [review]
lgtm

**Review by kamal-sutra — APPROVED** [review]

**Pull request merged**
