### PR TITLE
improve the price format on assets page

### PR DESCRIPTION
**Pull request by sunnya97**
### Linear Task

[Linear Task URL](PASTE_LINEAR_TASK_URL_HERE)

## Summary by CodeRabbit

- **Enhancements**
	- Improved the display formatting of asset prices in the `AssetsInfoTable` for clearer and more detailed financial information.

### CODE REVIEW

**Review by jonator — COMMENTED** [review]
Seems trailing 0s are not being accounted for:
cc @DavideSegullo 
Screenshot 2024-04-24 at 9 37 16 PM

**Comment by sunnya97** [comment]
No, that's on purpose, cause it should always have minimum 3 sig figs.

However, we should maybe switch this to use the "compacted zeros" from here:  https://github.com/osmosis-labs/osmosis-frontend/pull/3135/files

**Comment by jonator** [comment]
@sunnya97 do you still want to use compacted 0s? That seems to be the move now, I think CoinGecko does that

**Comment by sunnya97** [comment]
We can switch it to the compacted 0s, once the compacted 0s fix the trailing 0s issue

**Pull request merged**
