### PR TITLE
Remove concentratedLiquidity and its usages

### PR DESCRIPTION
**Pull request by UkuLoskit**
## What is the purpose of the change:

This PR address the issue https://github.com/osmosis-labs/osmosis-frontend/issues/3359

### Linear Task

N/A

## Brief Changelog

Removes the concentrated liquidity feature flag and its usages.

## Testing and Verifying

This change has been tested locally by rebuilding the website and verified content and links are expected

### CODE REVIEW

**Review by jonator — CHANGES_REQUESTED** [review]
Don't forget `assets-page-v1.tsx` usage of the flag

**Comment by UkuLoskit** [comment]
> Don't forget `assets-page-v1.tsx` usage of the flag

Somehow missed this. Addressed now.

**Comment by MaxMillington** [comment]
@CryptoAssassin1 @kamal-sutra can you test?

**Comment by CryptoAssassin1** [comment]
on it

**Comment by CryptoAssassin1** [comment]
@UkuLoskit please merge the stage into this branch.

**Comment by UkuLoskit** [comment]
> @UkuLoskit please merge the stage into this branch.

done

**Review by kamal-sutra — APPROVED** [review]

**Review by MaxMillington — APPROVED** [review]

**Comment by MaxMillington** [comment]
@UkuLoskit please reach out to finance@osmosis.team for the bounty payment

**Pull request merged**
