### PR TITLE
Add Thai  Language - Work in progress

### PR DESCRIPTION
**Pull request by daniel-farina**
This is a starting template for the Thai language.
- Everything needs to be revised, updated since many words are completely wrong but it's meant to be a starting point to make it easier. 

To contribute follow this guide and then PR back to this branch  `local/thai` or simply add contributions as comments and I'll update them.

https://docs.osmosis.zone/frontend/translating

Thanks!

### CODE REVIEW

**Comment by jonator** [comment]
Please update your branch from stage and diff your new json file against `en.json` to ensure you include any new translations that were recently added.

**Comment by jonator** [comment]
@daniel-farina this is well out of date and will need to be updated from master to include new translations

**Comment by jonator** [comment]
@daniel-farina could we get this across the finish line?

**Review by jonator — CHANGES_REQUESTED** [review]
Waiting for more and updated translations

**Comment by jonator** [comment]
Expired

**Comment by daniel-farina** [comment]
Re-opening this, might have some contributors this week to update from stage and then finish up the translation.

**Comment by jonator** [comment]
@daniel-farina any updates here?

**Comment by jonator** [comment]
I'm cleaning up PRs: please reopen when you get it to a state of review

**Pull request closed without merging**
