### PR TITLE
Fix: swap tool reset on page change

### PR DESCRIPTION
**Pull request by DavideSegullo**
In production, when I go to the detail page of a token and then change assets via the related assets section, the swap component does not update with the new default values to make the swap.
This PR fixes this misbehavior

### ClickUp Task

[ClickUp Task URL](PASTE_CLICKUP_TASK_URL_HERE)

### CODE REVIEW

**Review by jonator — COMMENTED** [review]
Is it ok if the token drawers can now be used to select other tokens? IMO it's fine as long as the tokens are set initially to the token for the current token page

**Comment by DavideSegullo** [comment]
> Is it ok if the token drawers can now be used to select other tokens? IMO it's fine as long as the tokens are set initially to the token for the current token page

Ye I think is fine, that's the right behaviour

**Comment by jonator** [comment]
@DavideSegullo actually I take it back the drawers aren't available anymore, but this is fixed

**Review by jonator — APPROVED** [review]

**Review by kamal-sutra — APPROVED** [review]
Fixed. works fine now

**Review by CryptoAssassin1 — APPROVED** [review]

**Pull request merged**
