### PR TITLE
run machine translate

### PR DESCRIPTION
**Pull request by mattupham**
## What is the purpose of the change

- run machine-translate

### ClickUp Task

[ClickUp Task URL](https://app.clickup.com/t/86a0zqcrc)

## Brief Changelog

- run machine translate for all langs

### CODE REVIEW

**Review by jonator — COMMENTED** [review]
Why do we need to re-run all of the translations? I think many of these were manually translated with app context in mind, which means they may be more accurate compared to 0 context google translations.

**Comment by MaxMillington** [comment]
@jonator when you say 'manually translated,' what do you mean? Did we contract an individual for certain translations?

**Comment by MaxMillington** [comment]
Incidentally, I've noticed differences between inlang, chatGPT, and google translate when going through translations

**Comment by jonator** [comment]
> @jonator when you say 'manually translated,' what do you mean? Did we contract an individual for certain translations?

Yeah we've had community and team language contributions that were done manually with full app context.

**Comment by jonator** [comment]
Is this hung up on an inlang bug still?

**Comment by jonator** [comment]
@mattupham that's what I was getting too. Looks like we need to reach out to inlang team again
@samuelstroschein

**Comment by samuelstroschein** [comment]
Hey @mattupham and @jonator, 

We will look into the bug(s) tomorrow (it's 12am in EU). 

On a side note, we are also adding validation for plugin settings which seem to be a root cause here given `(TypeError: Cannot read properties of undefined (reading 'variableReferencePattern')` is thrown. @jannesblobel is implementing the plugin setting validation.

**Comment by jonator** [comment]
@mattupham can you try updating this branch from stage? I think we merged a newer version of inlang

**Pull request closed without merging**
