### PR TITLE
Turkish localization

### PR DESCRIPTION
**Pull request by HuginnAcademy**
- Fixed missing translations
- Removed extra lines

### CODE REVIEW

**Review by jonator — CHANGES_REQUESTED** [review]
Please resolve conflicts with original tr.json file.

**Comment by HuginnAcademy** [comment]
Conflicts resolved.

**Review by jonator — APPROVED** [review]

**Comment by jonator** [comment]
Thanks!

**Comment by HuginnAcademy** [comment]
More than welcome, happy to have salt in the soup!

**Pull request merged**
