### PR TITLE
Turkish Language Added

### PR DESCRIPTION
**Pull request by HuginnAcademy**
Turkish crypto community is one of the largest in crypto. We felt the need to add Turkish as a language to Osmosis.

### CODE REVIEW

**Comment by jonator** [comment]
Please fix conflicts

**Comment by HuginnAcademy** [comment]
Should be fixed.

**Comment by jonator** [comment]
Thanks again :)

**Comment by jonator** [comment]
@HuginnAcademy Could you diff the current en.json with the current tr.json on the feat/redesign branch? I think there's quite a few translations missing

**Comment by HuginnAcademy** [comment]
Fixed in our branch.

**Pull request merged**
