### PR TITLE
Add Oraichain to Frontier

### PR DESCRIPTION
**Pull request by ducphamle2**

### CODE REVIEW

**Comment by kleimanb81** [comment]
@sunnya97 could you take a look at this?

**Comment by sunnya97** [comment]
Do you guys mind remaking this PR to assetlist as well.  Sorry, it got so stale.  Will merge both asap once ready

**Comment by ducphamle2** [comment]
sure thing. Let me clean the commits on Assetlist & push it

**Comment by ducphamle2** [comment]
But atm we have not come to an agreement regarding creating a pool on the frontier yet. Can the pool be added later on after the merge? We want to create a proposal on Oraichain to see if the community want to create a OSMO/ORAI pool

**Comment by kleimanb81** [comment]
But I'm putting in liq even if they vote no 😉

**Comment by ducphamle2** [comment]
@sunnya97 I have created a [new PR](https://github.com/osmosis-labs/assetlists/pull/228) on assetlists

**Review by JeremyParish69 — APPROVED** [review]

**Comment by JeremyParish69** [comment]
Please resolve conflicts then should be good to merge

**Comment by ducphamle2** [comment]
@JeremyParish69 conflicts resolved. Can you check again please?

**Pull request merged**
