### PR TITLE
change N/D on token info to be '-'

### PR DESCRIPTION
**Pull request by sunnya97**
### Linear Task

[Linear Task URL](PASTE_LINEAR_TASK_URL_HERE)

## Summary by CodeRabbit

- **Documentation**
	- Updated the display text for "noData" from "N.D." to "-" in English localization settings.
	- Updated various localization files to remove the "noData" key or translation, impacting the display of "no data" messages in multiple languages.

### CODE REVIEW

**Review by jonator — COMMENTED** [review]
Should this be in translations? Or removed from translations and installed in the view (where this key was formerly used)?

**Review by DavideSegullo — APPROVED** [review]

**Comment by DavideSegullo** [comment]
> Should this be in translations? Or removed from translations and installed in the view (where this key was formerly used)?

We're using it inside the token info page

**Review by jonator — DISMISSED** [review]
@DavideSegullo true but I don't think "-" needs to be translated, therefore it shouldn't be in the translation files?

**Comment by DavideSegullo** [comment]
> @DavideSegullo true but I don't think "-" needs to be translated, therefore it shouldn't be in the translation files? 

Ye we can get rid of It from translations

**Pull request merged**
