### PR TITLE
Publish Stage

### PR DESCRIPTION
**Pull request by jonator**
* Assets page: Reorder categories, limit price change to 1 decimal
* Hardcode lockable durations param
* Token Info: show swap tool on mobile/tablet (responsiveness)
* Tests and other end-user invisible changes
* Swap tool
   - when selecting a from token that matches the to token and vice-versa, swap the assets in the swap tool
* Swap tool
  - do an exact search for coinMinimalDenom first, if empty, continue the search for symbol / name
  - some examples to test with:
  -   milkTIA - factory/osmo1f5vfcph2dvfeqcqkhetwv75fda69z7e5c2dldm3kvgj23crkv6wqcn47a0/umilkTIA
  -   YieldETH - ibc/FBB3FEF80ED2344D821D4F95C31DBFD33E4E31D5324CAD94EF756E67B749F668
  -   ROAR - ibc/98BCD43F190C6960D0005BC46BB765C827403A361C9C03C2FF694150A30284B0
  - Revert fee subtraction from token out in favor of SQS response

### CODE REVIEW

**Review by p0mvn — CHANGES_REQUESTED** [review]
SQS 0.18.4 has to be deployed for this change to be applied in the production environment:
https://github.com/osmosis-labs/sqs/pull/223

ref: https://github.com/osmosis-labs/osmosis-frontend/pull/3262

Please confirm prod SQS deployment before stage publish

**Review by p0mvn — APPROVED** [review]
SQS taker fee deployment is complete

We currently charge the taker fee twice in the display until stage is published.

**Review by p0mvn — CHANGES_REQUESTED** [review]
SQS change was reverted. Let's coordinate on Monday

**Comment by jonator** [comment]
@p0mvn are we unblocked now? There's a UI fix with the category dropdown in assets page I'd like to get out

**Review by CryptoAssassin1 — APPROVED** [review]

**Comment by jonator** [comment]
Marking draft to do a coordinated release with SQS cc @p0mvn @MaxMillington

**Review by kamal-sutra — APPROVED** [review]

**Review by kamal-sutra — APPROVED** [review]

**Review by p0mvn — APPROVED** [review]
Working on sync deployment

**Pull request merged**
