### PR TITLE
Remove matomo analytics

### LINKED ISSUE #859: Remove Matomo analytics
Now that we have Amplitude, we should stop tracking Matomo analytics, and shut down all related services.

### PR DESCRIPTION
**Pull request by jonator**
Closes #859

### CODE REVIEW

**Comment by daniel-farina** [comment]
looks good!
When are we planning on doing QA on stage? do we have a lot of changes staged there?

**Comment by jonator** [comment]
No stage has no sitting features before this and is up to date with master

**Review by delivan — APPROVED** [review]
lgtm!

**Comment by jonator** [comment]
@daniel-farina don't forget to shut down matomo infra!

**Comment by daniel-farina** [comment]
I will shut it down once this is merge to master. Do we have a PR for the merge from stage to master?

**Pull request merged**
