### PR TITLE
Publish Stage

### PR DESCRIPTION
**Pull request by jonator**
## Brief Changelog

* Fixes swap tool when a returned route contains pools with assets not in asset list
* Earn page changes
    - Add default sorting for TVL
    - Remove the daily apr column
    - Fix search input, a separate pr from this had corrupted the style of this element
    - Copy changes
* IBC override link updates
* Wormhole integration improvements

### CODE REVIEW

**Comment by jonator** [comment]
> There is a CORS issue in stage. Let's not merge until it's resolved. I've notified the platform team.

@JoseRFelix is this fixed?

**Comment by JoseRFelix** [comment]
> is this fixed? Also BTW it'd be safer to convert this PR to a draft going forward to prevent it from accidentally being merged

Not yet, I'll work with the platform team to fix this today. I'll mark this PR as draft in the meantime, thank you

**Comment by JoseRFelix** [comment]
@jonator CORS issues have been fixed on stage 🙌

**Comment by jonator** [comment]
@JoseRFelix nice work, let's get some approvals

**Review by JoseRFelix — APPROVED** [review]

**Review by DavideSegullo — APPROVED** [review]

**Pull request merged**
